//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acq_Deal_Sport_Monetisation_Ancillary
    {
        public Acq_Deal_Sport_Monetisation_Ancillary()
        {
            this.Acq_Deal_Sport_Monetisation_Ancillary_Title = new HashSet<Acq_Deal_Sport_Monetisation_Ancillary_Title>();
            this.Acq_Deal_Sport_Monetisation_Ancillary_Type = new HashSet<Acq_Deal_Sport_Monetisation_Ancillary_Type>();
        }
    
    	public State EntityState { get; set; }    public int Acq_Deal_Sport_Monetisation_Ancillary_Code { get; set; }
    	    public Nullable<int> Acq_Deal_Code { get; set; }
    	    public string Appoint_Title_Sponsor { get; set; }
    	    public string Appoint_Broadcast_Sponsor { get; set; }
    	    public string Remarks { get; set; }
    
        public virtual Acq_Deal Acq_Deal { get; set; }
        public virtual ICollection<Acq_Deal_Sport_Monetisation_Ancillary_Title> Acq_Deal_Sport_Monetisation_Ancillary_Title { get; set; }
        public virtual ICollection<Acq_Deal_Sport_Monetisation_Ancillary_Type> Acq_Deal_Sport_Monetisation_Ancillary_Type { get; set; }
    }
}
