//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acq_Deal_Mass_Update_ErrorLog
    {
    	public State EntityState { get; set; }    public int Error_Log_Code { get; set; }
    	    public string Error_Message { get; set; }
    	    public Nullable<int> Acq_Deal_Mass_Update_Code { get; set; }
    	    public Nullable<System.DateTime> Error_Date { get; set; }
    
        public virtual Acq_Deal_Mass_Territory_Update Acq_Deal_Mass_Territory_Update { get; set; }
    }
}
