//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acq_Deal_Rights_Holdback
    {
        public Acq_Deal_Rights_Holdback()
        {
            this.Acq_Deal_Rights_Holdback_Platform = new HashSet<Acq_Deal_Rights_Holdback_Platform>();
            this.Acq_Deal_Rights_Holdback_Territory = new HashSet<Acq_Deal_Rights_Holdback_Territory>();
            this.Acq_Deal_Rights_Holdback_Dubbing = new HashSet<Acq_Deal_Rights_Holdback_Dubbing>();
            this.Acq_Deal_Rights_Holdback_Subtitling = new HashSet<Acq_Deal_Rights_Holdback_Subtitling>();
        }
    
    	public State EntityState { get; set; }    public int Acq_Deal_Rights_Holdback_Code { get; set; }
    	    public int Acq_Deal_Rights_Code { get; set; }
    	    public string Holdback_Type { get; set; }
    	    public Nullable<int> HB_Run_After_Release_No { get; set; }
    	    public string HB_Run_After_Release_Units { get; set; }
    	    public Nullable<int> Holdback_On_Platform_Code { get; set; }
    	    public Nullable<System.DateTime> Holdback_Release_Date { get; set; }
    	    public string Holdback_Comment { get; set; }
    	    public string Is_Title_Language_Right { get; set; }
    
        public virtual Acq_Deal_Rights Acq_Deal_Rights { get; set; }
        public virtual ICollection<Acq_Deal_Rights_Holdback_Platform> Acq_Deal_Rights_Holdback_Platform { get; set; }
        public virtual ICollection<Acq_Deal_Rights_Holdback_Territory> Acq_Deal_Rights_Holdback_Territory { get; set; }
        public virtual ICollection<Acq_Deal_Rights_Holdback_Dubbing> Acq_Deal_Rights_Holdback_Dubbing { get; set; }
        public virtual ICollection<Acq_Deal_Rights_Holdback_Subtitling> Acq_Deal_Rights_Holdback_Subtitling { get; set; }
    }
}
