//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AL_OEM
    {
        public AL_OEM()
        {
            this.AL_Vendor_OEM = new HashSet<AL_Vendor_OEM>();
            this.AL_Material_Tracking_OEM = new HashSet<AL_Material_Tracking_OEM>();
            this.AL_Material_Tracking = new HashSet<AL_Material_Tracking>();
        }
    
    	public State EntityState { get; set; }    public int AL_OEM_Code { get; set; }
    	    public string Company_Name { get; set; }
    	    public string Company_Short_Name { get; set; }
    	    public Nullable<int> Inserted_By { get; set; }
    	    public Nullable<System.DateTime> Inserted_On { get; set; }
    	    public Nullable<System.DateTime> Last_Updated_Time { get; set; }
    	    public Nullable<int> Last_Action_By { get; set; }
    	    public Nullable<System.DateTime> Lock_Time { get; set; }
    
        public virtual ICollection<AL_Vendor_OEM> AL_Vendor_OEM { get; set; }
        public virtual ICollection<AL_Material_Tracking_OEM> AL_Material_Tracking_OEM { get; set; }
        public virtual ICollection<AL_Material_Tracking> AL_Material_Tracking { get; set; }
    }
}
