//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AL_Recommendation_Content
    {
    	public State EntityState { get; set; }    public int AL_Recommendation_Content_Code { get; set; }
    	    public Nullable<int> AL_Recommendation_Code { get; set; }
    	    public Nullable<int> AL_Vendor_Rule_Code { get; set; }
    	    public Nullable<int> Title_Code { get; set; }
    	    public Nullable<int> Title_Content_Code { get; set; }
    	    public string Content_Type { get; set; }
    	    public string Content_Status { get; set; }
    
        public virtual AL_Recommendation AL_Recommendation { get; set; }
        public virtual AL_Vendor_Rule AL_Vendor_Rule { get; set; }
        public virtual Title Title { get; set; }
        public virtual Title_Content Title_Content { get; set; }
    }
}
