//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASRUN_Transaction_Shows
    {
    	public State EntityState { get; set; }    public decimal Asrun_Tr_Show_Id { get; set; }
    	    public string ON_AIR { get; set; }
    	    public string Dt_Tm { get; set; }
    	    public string ID { get; set; }
    	    public string S { get; set; }
    	    public string TITLE { get; set; }
    	    public string DURATION { get; set; }
    	    public string STATUS { get; set; }
    	    public string DEVICE { get; set; }
    	    public string CH { get; set; }
    	    public string RECONCILE { get; set; }
    	    public string TYP { get; set; }
    	    public string SEC { get; set; }
    	    public string Found_Status { get; set; }
    	    public Nullable<int> Title_Id { get; set; }
    	    public Nullable<long> FileCode { get; set; }
    	    public string IsProcessed { get; set; }
    	    public Nullable<int> ChannelCode { get; set; }
    	    public Nullable<decimal> Deal_Movie_Code { get; set; }
    	    public Nullable<decimal> Deal_Movie_Rights_Code { get; set; }
    	    public string HouseIdType { get; set; }
    	    public string IsException { get; set; }
    	    public Nullable<decimal> Deal_Movie_Content_Code { get; set; }
    	    public Nullable<decimal> Deal_Movie_Content_Channel_Rights_Code { get; set; }
    	    public string IsRunCount { get; set; }
    }
}
