//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsRun_FileStatus
    {
    	public State EntityState { get; set; }    public int AsRun_FileStatus_Code { get; set; }
    	    public Nullable<int> BVChannel_Code { get; set; }
    	    public Nullable<int> Channel_Code { get; set; }
    	    public string Channel_Name { get; set; }
    	    public string File_Name { get; set; }
    	    public Nullable<System.DateTime> AsRun_Date { get; set; }
    	    public string File_Status { get; set; }
    	    public string Remarks { get; set; }
    	    public string IsMail_Sent { get; set; }
    	    public Nullable<System.DateTime> AsRun_Execution_Date { get; set; }
    	    public Nullable<int> File_Code { get; set; }
    }
}
