//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avail_Acq
    {
        public Avail_Acq()
        {
            this.Avail_Acq_Details = new HashSet<Avail_Acq_Details>();
            this.Avail_Acq_Language = new HashSet<Avail_Acq_Language>();
        }
    
    	public State EntityState { get; set; }    public decimal Avail_Acq_Code { get; set; }
    	    public Nullable<int> Title_Code { get; set; }
    	    public Nullable<int> Platform_Code { get; set; }
    	    public Nullable<int> Country_Code { get; set; }
    	    public Nullable<int> Sub_Licencing_Code { get; set; }
    	    public Nullable<int> Territory_Code { get; set; }
    	    public string Territory_Type { get; set; }
    	    public Nullable<int> Eps_No { get; set; }
    
        public virtual ICollection<Avail_Acq_Details> Avail_Acq_Details { get; set; }
        public virtual ICollection<Avail_Acq_Language> Avail_Acq_Language { get; set; }
        public virtual Country Country { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual Title Title { get; set; }
    }
}
