//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broadcast_Mode
    {
        public Broadcast_Mode()
        {
            this.Acq_Deal_Sport_Broadcast = new HashSet<Acq_Deal_Sport_Broadcast>();
        }
    
    	public State EntityState { get; set; }    public int Broadcast_Mode_Code { get; set; }
    	    public string Broadcast_Mode_Name { get; set; }
    	    public string Mode_Key { get; set; }
    
        public virtual ICollection<Acq_Deal_Sport_Broadcast> Acq_Deal_Sport_Broadcast { get; set; }
    }
}
