//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BV_HouseId_Data_Shows
    {
    	public State EntityState { get; set; }    public int BV_HouseId_Data_Shows_Code { get; set; }
    	    public string House_Ids { get; set; }
    	    public string BV_Title { get; set; }
    	    public string Episode_No { get; set; }
    	    public Nullable<int> HouseID_Type_Code { get; set; }
    	    public Nullable<int> Mapped_Deal_Title_Code { get; set; }
    	    public string Is_Mapped { get; set; }
    	    public Nullable<int> Parent_BV_HouseId_Data_Code { get; set; }
    	    public Nullable<long> Upload_File_Code { get; set; }
    	    public string IsIgnore { get; set; }
    	    public string Upload_Type { get; set; }
    }
}
