//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BV_WBS
    {
    	public State EntityState { get; set; }    public int BV_WBS_Code { get; set; }
    	    public Nullable<int> SAP_WBS_Code { get; set; }
    	    public string WBS_Code { get; set; }
    	    public string WBS_Description { get; set; }
    	    public string Short_ID { get; set; }
    	    public string Is_Archive { get; set; }
    	    public string Status { get; set; }
    	    public string Error_Details { get; set; }
    	    public string Is_Process { get; set; }
    	    public Nullable<long> File_Code { get; set; }
    	    public Nullable<int> BV_Key { get; set; }
    	    public string Response_Type { get; set; }
    	    public string Response_Status { get; set; }
    
        public virtual SAP_WBS SAP_WBS { get; set; }
    }
}
