//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel_Region_Mapping
    {
    	public State EntityState { get; set; }    public int Channel_Region_Mapping_code { get; set; }
    	    public Nullable<int> Channel_Region_Code { get; set; }
    	    public Nullable<int> Channel_code { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual Channel_Region Channel_Region { get; set; }
    }
}
