//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel_Category_Details
    {
    	public State EntityState { get; set; }    public int Channel_Category_Details_Code { get; set; }
    	    public Nullable<int> Channel_Category_Code { get; set; }
    	    public Nullable<int> Channel_Code { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual Channel_Category Channel_Category { get; set; }
    }
}
