//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal_Workflow_Status
    {
    	public State EntityState { get; set; }    public int Deal_Workflow_Status_Code { get; set; }
    	    public string Deal_Workflow_Status_Name { get; set; }
    	    public string Deal_WorkflowFlag { get; set; }
    	    public string Deal_Type { get; set; }
    }
}
