//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal_Segment
    {
        public Deal_Segment()
        {
            this.Acq_Deal = new HashSet<Acq_Deal>();
            this.Syn_Deal = new HashSet<Syn_Deal>();
        }
    
    	public State EntityState { get; set; }    public int Deal_Segment_Code { get; set; }
    	    public string Deal_Segment_Name { get; set; }
    
        public virtual ICollection<Acq_Deal> Acq_Deal { get; set; }
        public virtual ICollection<Syn_Deal> Syn_Deal { get; set; }
    }
}
