//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Music_Title
    {
    	public State EntityState { get; set; }    public int IntCode { get; set; }
    	    public string Music_Title_Name { get; set; }
    	    public string Duration { get; set; }
    	    public string Movie_Album { get; set; }
    	    public string Singers { get; set; }
    	    public string Lyricist { get; set; }
    	    public string Music_Director { get; set; }
    	    public string Title_Language { get; set; }
    	    public string Music_Label { get; set; }
    	    public string Year_of_Release { get; set; }
    	    public string Title_Type { get; set; }
    	    public string Record_Status { get; set; }
    	    public string Error_Message { get; set; }
    	    public Nullable<int> DM_Master_Import_Code { get; set; }
    	    public string Genres { get; set; }
    	    public string Star_Cast { get; set; }
    	    public string Music_Version { get; set; }
    	    public string Effective_Start_Date { get; set; }
    	    public string Theme { get; set; }
    	    public string Music_Tag { get; set; }
    	    public string Movie_Star_Cast { get; set; }
    	    public string Music_Album_Type { get; set; }
    	    public string Excel_Line_No { get; set; }
    	    public string Is_Ignore { get; set; }
    	    public string Public_Domain { get; set; }
    }
}
