//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Title_Import_Utility
    {
    	public State EntityState { get; set; }    public int DM_Title_Import_Utility_Code { get; set; }
    	    public string Display_Name { get; set; }
    	    public Nullable<int> Order_No { get; set; }
    	    public string Target_Table { get; set; }
    	    public string Target_Column { get; set; }
    	    public string Colum_Type { get; set; }
    	    public string Is_Multiple { get; set; }
    	    public string Reference_Table { get; set; }
    	    public string Reference_Text_Field { get; set; }
    	    public string Reference_Value_Field { get; set; }
    	    public string Reference_Whr_Criteria { get; set; }
    	    public string Is_Active { get; set; }
    	    public string validation { get; set; }
    	    public string Is_Allowed_For_Resolve_Conflict { get; set; }
    	    public string ShortName { get; set; }
    }
}
