//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_Notification_AsRun
    {
    	public State EntityState { get; set; }    public decimal Email_Notification_AsRun_Code { get; set; }
    	    public Nullable<decimal> Asrun_Tr_Id { get; set; }
    	    public string ON_AIR { get; set; }
    	    public string Dt_Tm { get; set; }
    	    public string ID { get; set; }
    	    public string S { get; set; }
    	    public string TITLE { get; set; }
    	    public string DURATION { get; set; }
    	    public string STATUS { get; set; }
    	    public string DEVICE { get; set; }
    	    public string CH { get; set; }
    	    public string RECONCILE { get; set; }
    	    public string TYP { get; set; }
    	    public string SEC { get; set; }
    	    public Nullable<int> Title_Code { get; set; }
    	    public Nullable<int> File_Code { get; set; }
    	    public Nullable<int> Channel_Code { get; set; }
    	    public Nullable<System.DateTime> Inserted_On { get; set; }
    	    public Nullable<int> Deal_Movie_Code { get; set; }
    	    public Nullable<int> Deal_Movie_Rights_Code { get; set; }
    	    public string Email_Notification_Msg { get; set; }
    	    public string IsMailSent { get; set; }
    	    public string IsRunCountCalculate { get; set; }
    	    public string Title_Name { get; set; }
    	    public Nullable<System.DateTime> Right_Start_Date { get; set; }
    	    public Nullable<System.DateTime> Right_End_Date { get; set; }
    	    public string No_Of_Runs_Across_Beams { get; set; }
    	    public string Available_Channels { get; set; }
    	    public string Count_Of_AsRun { get; set; }
    	    public string Channel_Name { get; set; }
    }
}
