//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_Config_Detail_Alert
    {
    	public State EntityState { get; set; }    public int Email_Config_Detail_Alert_Code { get; set; }
    	    public Nullable<int> Email_Config_Detail_Code { get; set; }
    	    public Nullable<int> Mail_Alert_Days { get; set; }
    	    public string Allow_Less_Than { get; set; }
    
        public virtual Email_Config_Detail Email_Config_Detail { get; set; }
    }
}
