//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_Config_Detail_User
    {
    	public State EntityState { get; set; }    public int Email_Config_Detail_User_Code { get; set; }
    	    public Nullable<int> Email_Config_Detail_Code { get; set; }
    	    public string User_Type { get; set; }
    	    public Nullable<int> Security_Group_Code { get; set; }
    	    public string Business_Unit_Codes { get; set; }
    	    public string User_Codes { get; set; }
    	    public string Channel_Codes { get; set; }
    	    public string CC_Users { get; set; }
    	    public string BCC_Users { get; set; }
    	    public string ToUser_MailID { get; set; }
    	    public string CCUser_MailID { get; set; }
    	    public string BCCUser_MailID { get; set; }
    
        public virtual Email_Config_Detail Email_Config_Detail { get; set; }
    }
}
