//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Template_Keys
    {
        public Event_Template_Keys()
        {
            this.Email_Config_Keys = new HashSet<Email_Config_Keys>();
        }
    
    	public State EntityState { get; set; }    public int Event_Template_Keys_Code { get; set; }
    	    public string Key_Name { get; set; }
    	    public string Is_Active { get; set; }
    
        public virtual ICollection<Email_Config_Keys> Email_Config_Keys { get; set; }
    }
}
