//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Extended_Group
    {
        public Extended_Group()
        {
            this.Extended_Group_Config = new HashSet<Extended_Group_Config>();
        }
    
    	public State EntityState { get; set; }    public int Extended_Group_Code { get; set; }
    	    public string Group_Name { get; set; }
    	    public string Short_Name { get; set; }
    	    public Nullable<int> Group_Order { get; set; }
    	    public string Add_Edit_Type { get; set; }
    	    public Nullable<int> Module_Code { get; set; }
    	    public Nullable<int> Inserted_By { get; set; }
    	    public Nullable<System.DateTime> Inserted_On { get; set; }
    	    public Nullable<System.DateTime> Last_Updated_Time { get; set; }
    	    public Nullable<int> Last_Action_By { get; set; }
    	    public Nullable<System.DateTime> Lock_Time { get; set; }
    
        public virtual ICollection<Extended_Group_Config> Extended_Group_Config { get; set; }
    }
}
