//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImgPathData
    {
    	public State EntityState { get; set; }    public int Id { get; set; }
    	    public string ImgPath { get; set; }
    	    public string ImgData { get; set; }
    }
}
