//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPR_Rep_Channel
    {
    	public State EntityState { get; set; }    public int IPR_Rep_Channel_Code { get; set; }
    	    public Nullable<int> IPR_Rep_Code { get; set; }
    	    public Nullable<int> Channel_Code { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual IPR_REP IPR_REP { get; set; }
    }
}
