//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPR_Opp_Status_History
    {
    	public State EntityState { get; set; }    public int IPR_Opp_Status_History_Code { get; set; }
    	    public Nullable<int> IPR_Opp_Code { get; set; }
    	    public string IPR_Status { get; set; }
    	    public Nullable<System.DateTime> Changed_On { get; set; }
    	    public Nullable<int> Changed_By { get; set; }
    	    public string Remarks { get; set; }
    }
}
