//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPR_REP_CLASS
    {
    	public State EntityState { get; set; }    public int IPR_Rep_Class_Code { get; set; }
    	    public Nullable<int> IPR_Rep_Code { get; set; }
    	    public Nullable<int> IPR_Class_Code { get; set; }
    
        public virtual IPR_CLASS IPR_CLASS { get; set; }
        public virtual IPR_REP IPR_REP { get; set; }
    }
}
