//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map_Extended_Columns
    {
        public Map_Extended_Columns()
        {
            this.Map_Extended_Columns_Details = new HashSet<Map_Extended_Columns_Details>();
        }
    
    	public State EntityState { get; set; }    public int Map_Extended_Columns_Code { get; set; }
    	    public Nullable<int> Record_Code { get; set; }
    	    public string Table_Name { get; set; }
    	    public Nullable<int> Columns_Code { get; set; }
    	    public Nullable<int> Columns_Value_Code { get; set; }
    	    public string Column_Value { get; set; }
    	    public string Is_Multiple_Select { get; set; }
    
        public virtual Extended_Columns Extended_Columns { get; set; }
        public virtual Extended_Columns_Value Extended_Columns_Value { get; set; }
        public virtual ICollection<Map_Extended_Columns_Details> Map_Extended_Columns_Details { get; set; }
    }
}
