//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_Receipt_Order
    {
    	public State EntityState { get; set; }    public int Material_Receipt_Order1 { get; set; }
    	    public int Material_Receipt_Code { get; set; }
    	    public Nullable<int> Material_Order_Detail_Code { get; set; }
    	    public Nullable<int> Received_Qantity { get; set; }
    
        public virtual Material_Order_Details Material_Order_Details { get; set; }
        public virtual Material_Receipt Material_Receipt { get; set; }
    }
}
