//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHRequestDetail
    {
    	public State EntityState { get; set; }    public long MHRequestDetailsCode { get; set; }
    	    public Nullable<long> MHRequestCode { get; set; }
    	    public string TitleName { get; set; }
    	    public Nullable<int> LanguageCode { get; set; }
    	    public string MusicTrackName { get; set; }
    	    public string MusicLabelName { get; set; }
    	    public string MovieAlbum { get; set; }
    	    public string CreateMap { get; set; }
    	    public Nullable<int> ActionUserCode { get; set; }
    	    public Nullable<int> TitleCode { get; set; }
    	    public Nullable<int> MusicTitleCode { get; set; }
    	    public Nullable<int> MovieAlbumCode { get; set; }
    	    public string IsValid { get; set; }
    	    public string Remarks { get; set; }
    	    public Nullable<int> MusicLabelCode { get; set; }
    	    public string IsApprove { get; set; }
    	    public string ValidationMessage { get; set; }
    	    public string Singers { get; set; }
    	    public string StarCasts { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual MHRequest MHRequest { get; set; }
        public virtual Music_Album Music_Album { get; set; }
        public virtual Title Title { get; set; }
        public virtual Music_Label Music_Label { get; set; }
        public virtual Music_Title Music_Title { get; set; }
    }
}
