//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music_Schedule_Transaction
    {
    	public State EntityState { get; set; }    public decimal Music_Schedule_Transaction_Code { get; set; }
    	    public Nullable<decimal> BV_Schedule_Transaction_Code { get; set; }
    	    public Nullable<int> Content_Music_Link_Code { get; set; }
    	    public Nullable<int> Channel_Code { get; set; }
    	    public Nullable<int> Music_Label_Code { get; set; }
    	    public string Is_Ignore { get; set; }
    	    public string Is_Exception { get; set; }
    	    public string Is_Processed { get; set; }
    	    public Nullable<System.DateTime> Inserted_On { get; set; }
    	    public Nullable<int> Inserted_By { get; set; }
    	    public string Initial_Response { get; set; }
    	    public Nullable<int> Music_Override_Reason_Code { get; set; }
    	    public string Remarks { get; set; }
    	    public string Workflow_Status { get; set; }
    	    public string Is_Mail_Sent { get; set; }
    	    public Nullable<int> Music_Deal_Code { get; set; }
    }
}
