//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objection_Type
    {
    	public State EntityState { get; set; }    public int Objection_Type_Code { get; set; }
    	    public string Objection_Type_Name { get; set; }
    	    public string Is_Active { get; set; }
    }
}
