//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paf_Cost_Type_Mapping
    {
    	public State EntityState { get; set; }    public int Paf_Ctm_Code { get; set; }
    	    public string Paf_Cost_Type { get; set; }
    	    public Nullable<int> Ams_Cost_Type_Code { get; set; }
    	    public string Is_Mapped { get; set; }
    	    public Nullable<int> Upload_File_Code { get; set; }
    	    public string Upload_Type { get; set; }
    }
}
