//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paf_Cost_Type
    {
    	public State EntityState { get; set; }    public int Paf_Cost_Type_Code { get; set; }
    	    public Nullable<int> Paf_Code { get; set; }
    	    public int Paf_Ctm_Code { get; set; }
    	    public int Ams_Cost_Type_Code { get; set; }
    	    public Nullable<decimal> Amount { get; set; }
    	    public Nullable<decimal> Utilized { get; set; }
    	    public Nullable<decimal> Balance { get; set; }
    	    public string Entry_Type { get; set; }
    }
}
