//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provisional_Deal_Licensor
    {
    	public State EntityState { get; set; }    public int Provisional_Deal_Licensor_Code { get; set; }
    	    public Nullable<int> Provisional_Deal_Code { get; set; }
    	    public Nullable<int> Vendor_Code { get; set; }
    
        public virtual Provisional_Deal Provisional_Deal { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
