//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provisional_Deal
    {
        public Provisional_Deal()
        {
            this.Provisional_Deal_Licensor = new HashSet<Provisional_Deal_Licensor>();
            this.Provisional_Deal_Title = new HashSet<Provisional_Deal_Title>();
        }
    
    	public State EntityState { get; set; }    public int Provisional_Deal_Code { get; set; }
    	    public Nullable<int> Provisional_Deal_Type_Code { get; set; }
    	    public string Agreement_No { get; set; }
    	    public string Version { get; set; }
    	    public string Content_Type { get; set; }
    	    public Nullable<System.DateTime> Agreement_Date { get; set; }
    	    public Nullable<int> Deal_Type_Code { get; set; }
    	    public string Deal_Workflow_Status { get; set; }
    	    public string Is_Active { get; set; }
    	    public Nullable<int> Business_Unit_Code { get; set; }
    	    public string Remarks { get; set; }
    	    public string Deal_Desc { get; set; }
    	    public Nullable<System.DateTime> Right_Start_Date { get; set; }
    	    public Nullable<System.DateTime> Right_End_Date { get; set; }
    	    public string Term { get; set; }
    	    public Nullable<int> Acq_Deal_Code { get; set; }
    	    public Nullable<int> Inserted_By { get; set; }
    	    public Nullable<System.DateTime> Inserted_On { get; set; }
    	    public Nullable<System.DateTime> Last_Updated_Time { get; set; }
    	    public Nullable<int> Last_Action_By { get; set; }
    	    public Nullable<System.DateTime> Lock_Time { get; set; }
    	    public Nullable<int> Entity_Code { get; set; }
    
        public virtual Acq_Deal Acq_Deal { get; set; }
        public virtual Business_Unit Business_Unit { get; set; }
        public virtual Deal_Type Deal_Type { get; set; }
        public virtual ICollection<Provisional_Deal_Licensor> Provisional_Deal_Licensor { get; set; }
        public virtual Provisional_Deal_Type Provisional_Deal_Type { get; set; }
        public virtual ICollection<Provisional_Deal_Title> Provisional_Deal_Title { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
