//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Royalty_Recoupment_Details
    {
    	public State EntityState { get; set; }    public int Royalty_Recoupment_Details_Code { get; set; }
    	    public Nullable<int> Royalty_Recoupment_Code { get; set; }
    	    public string Recoupment_Type { get; set; }
    	    public Nullable<int> Recoupment_Type_Code { get; set; }
    	    public string Add_Subtract { get; set; }
    	    public Nullable<int> Position { get; set; }
    
        public virtual Royalty_Recoupment Royalty_Recoupment { get; set; }
    }
}
