//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplementary
    {
        public Supplementary()
        {
            this.Supplementary_Config = new HashSet<Supplementary_Config>();
        }
    
    	public State EntityState { get; set; }    public int Supplementary_Code { get; set; }
    	    public string Supplementary_Name { get; set; }
    	    public string Is_Active { get; set; }
    
        public virtual ICollection<Supplementary_Config> Supplementary_Config { get; set; }
    }
}
