//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Syn_Deal_Rights_Promoter
    {
        public Syn_Deal_Rights_Promoter()
        {
            this.Syn_Deal_Rights_Promoter_Group = new HashSet<Syn_Deal_Rights_Promoter_Group>();
            this.Syn_Deal_Rights_Promoter_Remarks = new HashSet<Syn_Deal_Rights_Promoter_Remarks>();
        }
    
    	public State EntityState { get; set; }    public int Syn_Deal_Rights_Promoter_Code { get; set; }
    	    public Nullable<int> Syn_Deal_Rights_Code { get; set; }
    	    public Nullable<System.DateTime> Inserted_On { get; set; }
    	    public Nullable<int> Inserted_By { get; set; }
    	    public Nullable<System.DateTime> Last_Updated_Time { get; set; }
    	    public Nullable<int> Last_Action_By { get; set; }
    
        public virtual Syn_Deal_Rights Syn_Deal_Rights { get; set; }
        public virtual ICollection<Syn_Deal_Rights_Promoter_Group> Syn_Deal_Rights_Promoter_Group { get; set; }
        public virtual ICollection<Syn_Deal_Rights_Promoter_Remarks> Syn_Deal_Rights_Promoter_Remarks { get; set; }
    }
}
