//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Syn_Deal_Ancillary_Platform
    {
        public Syn_Deal_Ancillary_Platform()
        {
            this.Syn_Deal_Ancillary_Platform_Medium = new HashSet<Syn_Deal_Ancillary_Platform_Medium>();
        }
    
    	public State EntityState { get; set; }    public int Syn_Deal_Ancillary_Platform_Code { get; set; }
    	    public Nullable<int> Syn_Deal_Ancillary_Code { get; set; }
    	    public Nullable<int> Ancillary_Platform_code { get; set; }
    
        public virtual Ancillary_Platform Ancillary_Platform { get; set; }
        public virtual Syn_Deal_Ancillary Syn_Deal_Ancillary { get; set; }
        public virtual ICollection<Syn_Deal_Ancillary_Platform_Medium> Syn_Deal_Ancillary_Platform_Medium { get; set; }
    }
}
