//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Syn_Deal_Rights_Subtitling
    {
    	public State EntityState { get; set; }    public int Syn_Deal_Rights_Subtitling_Code { get; set; }
    	    public Nullable<int> Syn_Deal_Rights_Code { get; set; }
    	    public string Language_Type { get; set; }
    	    public Nullable<int> Language_Code { get; set; }
    	    public Nullable<int> Language_Group_Code { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Language_Group Language_Group { get; set; }
        public virtual Syn_Deal_Rights Syn_Deal_Rights { get; set; }
    }
}
