//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Versions
    {
    	public State EntityState { get; set; }    public int Version_Code { get; set; }
    	    public string Version_No { get; set; }
    	    public string System_Name { get; set; }
    	    public Nullable<System.DateTime> Version_Published_Date { get; set; }
    	    public string Version_Details { get; set; }
    }
}
