//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TATStatusLog
    {
    	public State EntityState { get; set; }    public int TATStatusLogCode { get; set; }
    	    public Nullable<int> TATCode { get; set; }
    	    public Nullable<int> TATSLAStatusCode { get; set; }
    	    public Nullable<System.DateTime> StatusChangedOn { get; set; }
    	    public Nullable<int> StatusChangedBy { get; set; }
    
        public virtual TATSLAStatus TATSLAStatus { get; set; }
    }
}
