//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Territory_Details
    {
    	public State EntityState { get; set; }    public int Territory_Details_Code { get; set; }
    	    public int Country_Code { get; set; }
    	    public int Territory_Code { get; set; }
    	    public string Is_Ref_Acq { get; set; }
    	    public string Is_Ref_Syn { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Territory Territory { get; set; }
    }
}
