//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Territory_Deal_Log
    {
    	public State EntityState { get; set; }    public int Territory_Deal_Log_Code { get; set; }
    	    public Nullable<System.DateTime> Affected_Date { get; set; }
    	    public string Country_Codes { get; set; }
    	    public Nullable<int> Territory_Code { get; set; }
    	    public string Deal_Type { get; set; }
    	    public Nullable<int> Deal_Code { get; set; }
    	    public Nullable<int> Deal_Rights_Code { get; set; }
    	    public Nullable<int> User_Code { get; set; }
    }
}
