//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title_Alternate_Genres
    {
    	public State EntityState { get; set; }    public int Title_Alternate_Genres_Code { get; set; }
    	    public Nullable<int> Title_Alternate_Code { get; set; }
    	    public Nullable<int> Genres_Code { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Title_Alternate Title_Alternate { get; set; }
    }
}
