//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title_Alternate_Content
    {
    	public State EntityState { get; set; }    public int Title_Alternate_Content_Code { get; set; }
    	    public Nullable<int> Alternate_Config_Code { get; set; }
    	    public Nullable<int> Title_Alternate_Code { get; set; }
    	    public Nullable<int> Episode_No { get; set; }
    	    public string Content_Name { get; set; }
    	    public Nullable<int> Language_Code { get; set; }
    	    public string Synopsis { get; set; }
    	    public Nullable<decimal> Duration { get; set; }
    	    public string Title_Image { get; set; }
    	    public string Is_Active { get; set; }
    	    public Nullable<int> Inserted_By { get; set; }
    	    public Nullable<System.DateTime> Inserted_On { get; set; }
    	    public Nullable<System.DateTime> Last_UpDated_Time { get; set; }
    	    public Nullable<int> Last_Action_By { get; set; }
    	    public Nullable<System.DateTime> Lock_Time { get; set; }
    
        public virtual Alternate_Config Alternate_Config { get; set; }
        public virtual Title_Alternate Title_Alternate { get; set; }
    }
}
