//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload_Err_Detail
    {
    	public State EntityState { get; set; }    public long Upload_Detail_Code { get; set; }
       public long File_Code { get; set; }
    	    public Nullable<int> Row_Num { get; set; }
    	    public string Row_Delimed { get; set; }
    	    public string Err_Cols { get; set; }
    	    public string Upload_Type { get; set; }
    	    public string Upload_Title_Type { get; set; }
    }
}
