//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Channel
    {
    	public State EntityState { get; set; }    public int Users_Channel_Code { get; set; }
    	    public Nullable<int> Users_Code { get; set; }
    	    public Nullable<int> Channel_Code { get; set; }
    	    public string S_Default { get; set; }
    
        public virtual User User { get; set; }
    }
}
