//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_InterimDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow_BU_Role
    {
        public Workflow_BU_Role()
        {
            this.Workflow_Module_BU_Role = new HashSet<Workflow_Module_BU_Role>();
        }
    
    	public State EntityState { get; set; }    public int Workflow_BU_Role_Code { get; set; }
    	    public Nullable<short> Group_Level { get; set; }
    	    public Nullable<int> Workflow_BU_Code { get; set; }
    	    public Nullable<int> Security_Group_Code { get; set; }
    
        public virtual Security_Group Security_Group { get; set; }
        public virtual Workflow_BU Workflow_BU { get; set; }
        public virtual ICollection<Workflow_Module_BU_Role> Workflow_Module_BU_Role { get; set; }
    }
}
