CREATE TYPE [dbo].[Avail_Report_Schedule_Data] AS TABLE (
    [Title_Code]            VARCHAR (MAX)  NULL,
    [Country_Code]          VARCHAR (MAX)  NULL,
    [Platform_Code]         VARCHAR (MAX)  NULL,
    [Is_Original_Language]  VARCHAR (MAX)  NULL,
    [Dubbing_Subtitling]    VARCHAR (MAX)  NULL,
    [Language_Code]         VARCHAR (MAX)  NULL,
    [Date_Type]             VARCHAR (2)    NULL,
    [StartDate]             VARCHAR (MAX)  NULL,
    [EndDate]               VARCHAR (MAX)  NULL,
    [UserCode]              INT            NULL,
    [Inserted_On]           DATETIME       NULL,
    [Report_Status]         CHAR (1)       NULL,
    [Visibility]            CHAR (2)       NULL,
    [ReportName]            NVARCHAR (MAX) NULL,
    [RestrictionRemark]     VARCHAR (MAX)  NULL,
    [OtherRemark]           VARCHAR (MAX)  NULL,
    [Platform_ExactMatch]   CHAR (10)      NULL,
    [MustHave_Platform]     VARCHAR (MAX)  NULL,
    [Exclusivity]           CHAR (1)       NULL,
    [SubLicenseCode]        VARCHAR (MAX)  NULL,
    [Region_ExactMatch]     CHAR (10)      NULL,
    [Region_MustHave]       VARCHAR (MAX)  NULL,
    [Region_Exclusion]      VARCHAR (MAX)  NULL,
    [Subtit_Language_Code]  VARCHAR (MAX)  NULL,
    [Dubbing_Language_Code] VARCHAR (MAX)  NULL,
    [BU_Code]               INT            NULL,
    [Report_Type]           CHAR (2)       NULL,
    [Digital]               BIT            NULL,
    [IncludeMetadata]       VARCHAR (MAX)  NULL,
    [Is_IFTA_Cluster]       CHAR (1)       NULL,
    [Platform_Group_Code]   VARCHAR (MAX)  NULL,
    [Subtitling_Group_Code] VARCHAR (MAX)  NULL,
    [Subtitling_ExactMatch] CHAR (10)      NULL,
    [Subtitling_MustHave]   VARCHAR (MAX)  NULL,
    [Subtitling_Exclusion]  VARCHAR (MAX)  NULL,
    [Dubbing_Group_Code]    VARCHAR (MAX)  NULL,
    [Dubbing_ExactMatch]    CHAR (10)      NULL,
    [Dubbing_MustHave]      VARCHAR (MAX)  NULL,
    [Dubbing_Exclusion]     VARCHAR (MAX)  NULL,
    [Territory_Code]        VARCHAR (MAX)  NULL,
    [IndiaCast]             CHAR (1)       NULL,
    [Region_On]             CHAR (2)       NULL,
    [Include_Ancillary]     CHAR (1)       NULL,
    [Promoter_Code]         VARCHAR (MAX)  NULL,
    [MustHave_Promoter]     VARCHAR (MAX)  NULL,
    [Promoter_ExactMatch]   VARCHAR (MAX)  NULL,
    [Module_Code]           INT            NULL,
    [Episode_From]          INT            NULL,
    [Episode_To]            INT            NULL);

