CREATE TABLE [dbo].[Acq_Deal] (
    [Acq_Deal_Code]                 INT             IDENTITY (1, 1) NOT NULL,
    [Agreement_No]                  VARCHAR (50)    NULL,
    [Version]                       VARCHAR (50)    NULL,
    [Agreement_Date]                DATETIME        NULL,
    [Deal_Desc]                     NVARCHAR (1000) NULL,
    [Deal_Type_Code]                INT             NULL,
    [Year_Type]                     CHAR (2)        NULL,
    [Entity_Code]                   INT             NULL,
    [Is_Master_Deal]                CHAR (1)        NULL,
    [Category_Code]                 INT             NULL,
    [Vendor_Code]                   INT             NULL,
    [Vendor_Contacts_Code]          INT             NOT NULL,
    [Currency_Code]                 INT             NULL,
    [Exchange_Rate]                 NUMERIC (10, 3) NULL,
    [Ref_No]                        NVARCHAR (100)  NULL,
    [Attach_Workflow]               CHAR (1)        CONSTRAINT [DF_Acq_Deal_Attach_Workflow] DEFAULT ('N') NULL,
    [Deal_Workflow_Status]          VARCHAR (50)    CONSTRAINT [DF_Acq_Deal_Acq_Deal_Workflow_Status] DEFAULT ('N') NULL,
    [Parent_Deal_Code]              INT             NULL,
    [Work_Flow_Code]                INT             NULL,
    [Amendment_Date]                DATETIME        NULL,
    [Is_Released]                   CHAR (1)        CONSTRAINT [DF_Acq_Deal_IsReleased] DEFAULT ('N') NULL,
    [Release_On]                    DATETIME        NULL,
    [Release_By]                    INT             NULL,
    [Is_Completed]                  CHAR (1)        CONSTRAINT [DF_Acq_Deal_Is_Completed] DEFAULT ('N') NULL,
    [Is_Active]                     CHAR (1)        CONSTRAINT [DF_Acq_Deal_Is_Active] DEFAULT ('Y') NULL,
    [Content_Type]                  CHAR (2)        NULL,
    [Payment_Terms_Conditions]      NVARCHAR (4000) NULL,
    [Status]                        CHAR (1)        NULL,
    [Is_Auto_Generated]             CHAR (1)        CONSTRAINT [DF_Acq_Deal_Is_Auto_Generated_1] DEFAULT ('N') NULL,
    [Is_Migrated]                   CHAR (1)        CONSTRAINT [DF_Acq_Deal_Is_Migrated] DEFAULT ('N') NULL,
    [Cost_Center_Id]                INT             NULL,
    [Master_Deal_Movie_Code_ToLink] INT             NULL,
    [BudgetWise_Costing_Applicable] VARCHAR (2)     NULL,
    [Validate_CostWith_Budget]      VARCHAR (2)     NULL,
    [Deal_Tag_Code]                 INT             NULL,
    [Business_Unit_Code]            INT             NULL,
    [Ref_BMS_Code]                  VARCHAR (100)   NULL,
    [Remarks]                       NVARCHAR (4000) NULL,
    [Rights_Remarks]                NVARCHAR (4000) NULL,
    [Payment_Remarks]               NVARCHAR (4000) NULL,
    [Deal_Complete_Flag]            VARCHAR (100)   NULL,
    [Inserted_By]                   INT             NULL,
    [Inserted_On]                   DATETIME        NULL,
    [Last_Updated_Time]             DATETIME        NULL,
    [Last_Action_By]                INT             NULL,
    [Lock_Time]                     DATETIME        NULL,
    [All_Channel]                   VARCHAR (1)     NULL,
    [Role_Code]                     INT             NULL,
    [Channel_Cluster_Code]          INT             NULL,
    [Is_Auto_Push]					CHAR(1)			DEFAULT 'N', 
    CONSTRAINT [PK_Acq_Deal] PRIMARY KEY CLUSTERED ([Acq_Deal_Code] ASC),
    CONSTRAINT [FK_Acq_Deal_Acq_Deal_Tag] FOREIGN KEY ([Deal_Tag_Code]) REFERENCES [dbo].[Deal_Tag] ([Deal_Tag_Code]),
    CONSTRAINT [FK_Acq_Deal_Acq_Deal_Type] FOREIGN KEY ([Deal_Type_Code]) REFERENCES [dbo].[Deal_Type] ([Deal_Type_Code]),
    CONSTRAINT [FK_Acq_Deal_Business_Unit] FOREIGN KEY ([Business_Unit_Code]) REFERENCES [dbo].[Business_Unit] ([Business_Unit_Code]),
    CONSTRAINT [FK_Acq_Deal_Category] FOREIGN KEY ([Category_Code]) REFERENCES [dbo].[Category] ([Category_Code]),
    CONSTRAINT [FK_Acq_Deal_Channel_Cluster] FOREIGN KEY ([Channel_Cluster_Code]) REFERENCES [dbo].[Channel_Cluster] ([Channel_Cluster_Code]),
    CONSTRAINT [FK_Acq_Deal_Cost_Center] FOREIGN KEY ([Cost_Center_Id]) REFERENCES [dbo].[Cost_Center] ([Cost_Center_Id]),
    CONSTRAINT [FK_Acq_Deal_Currency] FOREIGN KEY ([Currency_Code]) REFERENCES [dbo].[Currency] ([Currency_Code]),
    CONSTRAINT [FK_Acq_Deal_Entity] FOREIGN KEY ([Entity_Code]) REFERENCES [dbo].[Entity] ([Entity_Code]),
    CONSTRAINT [FK_Acq_Deal_Role] FOREIGN KEY ([Role_Code]) REFERENCES [dbo].[Role] ([Role_Code]),
    CONSTRAINT [FK_Acq_Deal_Vendor] FOREIGN KEY ([Vendor_Code]) REFERENCES [dbo].[Vendor] ([Vendor_Code]),
    CONSTRAINT [FK_Acq_Deal_Workflow] FOREIGN KEY ([Work_Flow_Code]) REFERENCES [dbo].[Workflow] ([Workflow_Code])
);



