CREATE TABLE [dbo].[AL_Material_Tracking] (
    [AL_Material_Tracking_Code] INT           IDENTITY (1, 1) NOT NULL,
    [Title_Code]                INT           NULL,
    [Title_Content_Code]        INT           NULL,
    [Vendor_Code]               INT           NULL,
    [AL_Lab_Code]               INT           NULL,
    [PO_Number]                 VARCHAR (50)  NULL,
    [PO_Status]                 VARCHAR (50)  NULL,
    [AL_OEM_Code]               INT           NULL,
    [OEM_File_Name]             VARCHAR (500) NULL,
    [Delivery_Date]             DATE          NULL,
    [Poster]                    VARCHAR (50)  NULL,
    [Still]                     VARCHAR (50)  NULL,
    [Trailer]                   VARCHAR (50)  NULL,
    [Embedded_Subs]             VARCHAR (500) NULL,
    [Edited_Poster]             VARCHAR (50)  NULL,
    [Edited_Still]              VARCHAR (50)  NULL,
    [Master_In_House]           VARCHAR (500) NULL,
    [Status]                    CHAR (1)      NULL,
    [Due_Date]                  VARCHAR (100) NULL,
    [AL_Proposal_Code]          INT           NULL,
    CONSTRAINT [PK_AL_Material_Tracking] PRIMARY KEY CLUSTERED ([AL_Material_Tracking_Code] ASC),
    CONSTRAINT [FK_AL_Material_Tracking_AL_Lab] FOREIGN KEY ([AL_Lab_Code]) REFERENCES [dbo].[AL_Lab] ([AL_Lab_Code]),
    CONSTRAINT [FK_AL_Material_Tracking_AL_OEM] FOREIGN KEY ([AL_OEM_Code]) REFERENCES [dbo].[AL_OEM] ([AL_OEM_Code]),
    CONSTRAINT [FK_AL_Material_Tracking_AL_Proposal] FOREIGN KEY ([AL_Proposal_Code]) REFERENCES [dbo].[AL_Proposal] ([AL_Proposal_Code]),
    CONSTRAINT [FK_AL_Material_Tracking_Title] FOREIGN KEY ([Title_Code]) REFERENCES [dbo].[Title] ([Title_Code]),
    CONSTRAINT [FK_AL_Material_Tracking_Title_Content] FOREIGN KEY ([Title_Content_Code]) REFERENCES [dbo].[Title_Content] ([Title_Content_Code]),
    CONSTRAINT [FK_AL_Material_Tracking_Vendor] FOREIGN KEY ([Vendor_Code]) REFERENCES [dbo].[Vendor] ([Vendor_Code])
);

