CREATE TABLE [dbo].[ASRUN_Transaction_Shows] (
    [Asrun_Tr_Show_Id]                       NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [ON_AIR]                                 VARCHAR (250)  NULL,
    [Dt_Tm]                                  VARCHAR (250)  NULL,
    [ID]                                     VARCHAR (1000) NULL,
    [S]                                      VARCHAR (250)  NULL,
    [TITLE]                                  VARCHAR (250)  NULL,
    [DURATION]                               VARCHAR (250)  NULL,
    [STATUS]                                 VARCHAR (250)  NULL,
    [DEVICE]                                 VARCHAR (250)  NULL,
    [CH]                                     VARCHAR (250)  NULL,
    [RECONCILE]                              VARCHAR (250)  NULL,
    [TYP]                                    VARCHAR (250)  NULL,
    [SEC]                                    VARCHAR (250)  NULL,
    [Found_Status]                           CHAR (1)       NULL,
    [Title_Id]                               INT            NULL,
    [FileCode]                               BIGINT         NULL,
    [IsProcessed]                            CHAR (1)       NULL,
    [ChannelCode]                            INT            NULL,
    [Deal_Movie_Code]                        NUMERIC (18)   NULL,
    [Deal_Movie_Rights_Code]                 NUMERIC (18)   NULL,
    [HouseIdType]                            VARCHAR (1000) NULL,
    [IsException]                            CHAR (1)       NULL,
    [Deal_Movie_Content_Code]                NUMERIC (18)   NULL,
    [Deal_Movie_Content_Channel_Rights_Code] NUMERIC (18)   NULL,
    [IsRunCount]                             VARCHAR (10)   NULL,
    CONSTRAINT [PK_ASRUN_Transaction_Shows] PRIMARY KEY CLUSTERED ([Asrun_Tr_Show_Id] ASC)
);

