CREATE TABLE [dbo].[DM_AQDeal] (
    [Deal Number]                           FLOAT (53)     NULL,
    [Deal Signed_ Date]                     DATETIME       NULL,
    [Deal Description]                      NVARCHAR (255) NULL,
    [Status]                                NVARCHAR (255) NULL,
    [Deal type]                             NVARCHAR (255) NULL,
    [Link Sub Deal to Master Deal]          NVARCHAR (255) NULL,
    [Mode of Acquisition]                   NVARCHAR (255) NULL,
    [Deal For]                              NVARCHAR (255) NULL,
    [Currency]                              NVARCHAR (255) NULL,
    [Licensee / Assignee]                   NVARCHAR (255) NULL,
    [Licensor/Assignor/Producer]            NVARCHAR (255) NULL,
    [Category]                              NVARCHAR (255) NULL,
    [Reference No]                          NVARCHAR (255) NULL,
    [Title]                                 NVARCHAR (255) NULL,
    [Remarks]                               NVARCHAR (255) NULL,
    [1]                                     NVARCHAR (255) NULL,
    [18]                                    NVARCHAR (255) NULL,
    [19]                                    NVARCHAR (255) NULL,
    [84]                                    NVARCHAR (255) NULL,
    [85]                                    NVARCHAR (255) NULL,
    [21]                                    NVARCHAR (255) NULL,
    [22]                                    NVARCHAR (255) NULL,
    [23]                                    NVARCHAR (255) NULL,
    [24]                                    NVARCHAR (255) NULL,
    [86]                                    NVARCHAR (255) NULL,
    [87]                                    NVARCHAR (255) NULL,
    [88]                                    NVARCHAR (255) NULL,
    [89]                                    NVARCHAR (255) NULL,
    [90]                                    NVARCHAR (255) NULL,
    [91]                                    NVARCHAR (255) NULL,
    [28]                                    NVARCHAR (255) NULL,
    [92]                                    NVARCHAR (255) NULL,
    [93]                                    NVARCHAR (255) NULL,
    [94]                                    NVARCHAR (255) NULL,
    [95]                                    NVARCHAR (255) NULL,
    [96]                                    NVARCHAR (255) NULL,
    [97]                                    NVARCHAR (255) NULL,
    [98]                                    NVARCHAR (255) NULL,
    [99]                                    NVARCHAR (255) NULL,
    [100]                                   NVARCHAR (255) NULL,
    [101]                                   NVARCHAR (255) NULL,
    [33]                                    NVARCHAR (255) NULL,
    [34]                                    NVARCHAR (255) NULL,
    [35]                                    NVARCHAR (255) NULL,
    [36]                                    NVARCHAR (255) NULL,
    [37]                                    NVARCHAR (255) NULL,
    [38]                                    NVARCHAR (255) NULL,
    [6]                                     NVARCHAR (255) NULL,
    [102]                                   NVARCHAR (255) NULL,
    [166]                                   NVARCHAR (255) NULL,
    [167]                                   NVARCHAR (255) NULL,
    [168]                                   NVARCHAR (255) NULL,
    [169]                                   NVARCHAR (255) NULL,
    [170]                                   NVARCHAR (255) NULL,
    [105]                                   NVARCHAR (255) NULL,
    [171]                                   NVARCHAR (255) NULL,
    [172]                                   NVARCHAR (255) NULL,
    [173]                                   NVARCHAR (255) NULL,
    [174]                                   NVARCHAR (255) NULL,
    [175]                                   NVARCHAR (255) NULL,
    [176]                                   NVARCHAR (255) NULL,
    [177]                                   NVARCHAR (255) NULL,
    [178]                                   NVARCHAR (255) NULL,
    [179]                                   NVARCHAR (255) NULL,
    [180]                                   NVARCHAR (255) NULL,
    [181]                                   NVARCHAR (255) NULL,
    [182]                                   NVARCHAR (255) NULL,
    [183]                                   NVARCHAR (255) NULL,
    [184]                                   NVARCHAR (255) NULL,
    [185]                                   NVARCHAR (255) NULL,
    [186]                                   NVARCHAR (255) NULL,
    [187]                                   NVARCHAR (255) NULL,
    [188]                                   NVARCHAR (255) NULL,
    [189]                                   NVARCHAR (255) NULL,
    [190]                                   NVARCHAR (255) NULL,
    [191]                                   NVARCHAR (255) NULL,
    [192]                                   NVARCHAR (255) NULL,
    [193]                                   NVARCHAR (255) NULL,
    [194]                                   NVARCHAR (255) NULL,
    [195]                                   NVARCHAR (255) NULL,
    [196]                                   NVARCHAR (255) NULL,
    [197]                                   NVARCHAR (255) NULL,
    [198]                                   NVARCHAR (255) NULL,
    [199]                                   NVARCHAR (255) NULL,
    [200]                                   NVARCHAR (255) NULL,
    [201]                                   NVARCHAR (255) NULL,
    [202]                                   NVARCHAR (255) NULL,
    [203]                                   NVARCHAR (255) NULL,
    [117]                                   NVARCHAR (255) NULL,
    [118]                                   NVARCHAR (255) NULL,
    [119]                                   NVARCHAR (255) NULL,
    [120]                                   NVARCHAR (255) NULL,
    [121]                                   NVARCHAR (255) NULL,
    [122]                                   NVARCHAR (255) NULL,
    [204]                                   NVARCHAR (255) NULL,
    [205]                                   NVARCHAR (255) NULL,
    [206]                                   NVARCHAR (255) NULL,
    [207]                                   NVARCHAR (255) NULL,
    [208]                                   NVARCHAR (255) NULL,
    [209]                                   NVARCHAR (255) NULL,
    [210]                                   NVARCHAR (255) NULL,
    [211]                                   NVARCHAR (255) NULL,
    [212]                                   NVARCHAR (255) NULL,
    [213]                                   NVARCHAR (255) NULL,
    [126]                                   NVARCHAR (255) NULL,
    [127]                                   NVARCHAR (255) NULL,
    [128]                                   NVARCHAR (255) NULL,
    [129]                                   NVARCHAR (255) NULL,
    [130]                                   NVARCHAR (255) NULL,
    [131]                                   NVARCHAR (255) NULL,
    [45]                                    NVARCHAR (255) NULL,
    [46]                                    NVARCHAR (255) NULL,
    [47]                                    NVARCHAR (255) NULL,
    [48]                                    NVARCHAR (255) NULL,
    [49]                                    NVARCHAR (255) NULL,
    [50]                                    NVARCHAR (255) NULL,
    [51]                                    NVARCHAR (255) NULL,
    [52]                                    NVARCHAR (255) NULL,
    [53]                                    NVARCHAR (255) NULL,
    [54]                                    NVARCHAR (255) NULL,
    [55]                                    NVARCHAR (255) NULL,
    [56]                                    NVARCHAR (255) NULL,
    [57]                                    NVARCHAR (255) NULL,
    [132]                                   NVARCHAR (255) NULL,
    [133]                                   NVARCHAR (255) NULL,
    [134]                                   NVARCHAR (255) NULL,
    [135]                                   NVARCHAR (255) NULL,
    [136]                                   NVARCHAR (255) NULL,
    [137]                                   NVARCHAR (255) NULL,
    [138]                                   NVARCHAR (255) NULL,
    [139]                                   NVARCHAR (255) NULL,
    [140]                                   NVARCHAR (255) NULL,
    [141]                                   NVARCHAR (255) NULL,
    [142]                                   NVARCHAR (255) NULL,
    [143]                                   NVARCHAR (255) NULL,
    [144]                                   NVARCHAR (255) NULL,
    [145]                                   NVARCHAR (255) NULL,
    [146]                                   NVARCHAR (255) NULL,
    [147]                                   NVARCHAR (255) NULL,
    [148]                                   NVARCHAR (255) NULL,
    [149]                                   NVARCHAR (255) NULL,
    [150]                                   NVARCHAR (255) NULL,
    [151]                                   NVARCHAR (255) NULL,
    [152]                                   NVARCHAR (255) NULL,
    [153]                                   NVARCHAR (255) NULL,
    [154]                                   NVARCHAR (255) NULL,
    [155]                                   NVARCHAR (255) NULL,
    [156]                                   NVARCHAR (255) NULL,
    [157]                                   NVARCHAR (255) NULL,
    [158]                                   NVARCHAR (255) NULL,
    [159]                                   NVARCHAR (255) NULL,
    [160]                                   NVARCHAR (255) NULL,
    [161]                                   NVARCHAR (255) NULL,
    [64]                                    NVARCHAR (255) NULL,
    [65]                                    NVARCHAR (255) NULL,
    [66]                                    NVARCHAR (255) NULL,
    [67]                                    NVARCHAR (255) NULL,
    [68]                                    NVARCHAR (255) NULL,
    [69]                                    NVARCHAR (255) NULL,
    [70]                                    NVARCHAR (255) NULL,
    [71]                                    NVARCHAR (255) NULL,
    [72]                                    NVARCHAR (255) NULL,
    [73]                                    NVARCHAR (255) NULL,
    [74]                                    NVARCHAR (255) NULL,
    [75]                                    NVARCHAR (255) NULL,
    [76]                                    NVARCHAR (255) NULL,
    [77]                                    NVARCHAR (255) NULL,
    [78]                                    NVARCHAR (255) NULL,
    [16]                                    NVARCHAR (255) NULL,
    [214]                                   NVARCHAR (255) NULL,
    [215]                                   NVARCHAR (255) NULL,
    [216]                                   NVARCHAR (255) NULL,
    [217]                                   NVARCHAR (255) NULL,
    [218]                                   NVARCHAR (255) NULL,
    [219]                                   NVARCHAR (255) NULL,
    [165]                                   NVARCHAR (255) NULL,
    [81]                                    NVARCHAR (255) NULL,
    [82]                                    NVARCHAR (255) NULL,
    [83]                                    NVARCHAR (255) NULL,
    [Country]                               NVARCHAR (255) NULL,
    [Territory]                             NVARCHAR (255) NULL,
    [Exclusive]                             NVARCHAR (255) NULL,
    [Deal Term ]                            NVARCHAR (255) NULL,
    [Tenative Start Date]                   NVARCHAR (255) NULL,
    [Start Date]                            DATETIME       NULL,
    [End Date]                              DATETIME       NULL,
    [Original Language Right ]              NVARCHAR (255) NULL,
    [Sub Licensing]                         NVARCHAR (255) NULL,
    [Sub Titling]                           NVARCHAR (255) NULL,
    [Dubbing]                               NVARCHAR (255) NULL,
    [Rights for First Refusal Trigger date] DATETIME       NULL,
    [Rights Restriction Remarks]            NVARCHAR (255) NULL,
    [Holdback On  Licensee]                 NVARCHAR (255) NULL,
    [Holdback Date]                         NVARCHAR (255) NULL,
    [Holdback Comments]                     NVARCHAR (255) NULL,
    [Blackout Start Date]                   DATETIME       NULL,
    [Blackout End Date]                     DATETIME       NULL,
    [No# of Runs]                           NVARCHAR (255) NULL,
    [Yearly Runs]                           NVARCHAR (255) NULL,
    [Rights Rule]                           NVARCHAR (255) NULL,
    [All MSM Channels]                      NVARCHAR (255) NULL,
    [Shared Rights]                         NVARCHAR (255) NULL,
    [AXN India]                             NVARCHAR (255) NULL,
    [MIX India]                             NVARCHAR (255) NULL,
    [MIX International]                     NVARCHAR (255) NULL,
    [SET India]                             NVARCHAR (255) NULL,
    [SET ME]                                NVARCHAR (255) NULL,
    [SET HD]                                NVARCHAR (255) NULL,
    [SET HD US]                             NVARCHAR (255) NULL,
    [SET International]                     NVARCHAR (255) NULL,
    [SET Africa]                            NVARCHAR (255) NULL,
    [SET HD Canada]                         NVARCHAR (255) NULL,
    [SET United Kingdom]                    NVARCHAR (255) NULL,
    [SET United States]                     NVARCHAR (255) NULL,
    [SAB India]                             NVARCHAR (255) NULL,
    [SAB US]                                NVARCHAR (255) NULL,
    [SAB International]                     NVARCHAR (255) NULL,
    [SAB United Kingdom]                    NVARCHAR (255) NULL,
    [MAX India]                             NVARCHAR (255) NULL,
    [MAX Africa]                            NVARCHAR (255) NULL,
    [MAX International]                     NVARCHAR (255) NULL,
    [MAX Canada]                            NVARCHAR (255) NULL,
    [MAX United Kingdom]                    NVARCHAR (255) NULL,
    [MAX United States]                     NVARCHAR (255) NULL,
    [MAX Middle East]                       NVARCHAR (255) NULL,
    [PIX India]                             NVARCHAR (255) NULL,
    [PIX HD]                                NVARCHAR (255) NULL,
    [Sony Aath]                             NVARCHAR (255) NULL,
    [SIX (On Air)]                          NVARCHAR (255) NULL,
    [SIX HD (On Air)]                       NVARCHAR (255) NULL,
    [MAX 2]                                 NVARCHAR (255) NULL,
    [Sony Pal]                              NVARCHAR (255) NULL,
    [Restriction Window]                    NVARCHAR (255) NULL,
    [Time Lag (Simulcast)]                  NVARCHAR (255) NULL,
    [IntCode]                               INT            IDENTITY (1, 1) NOT NULL
);

