CREATE TABLE [dbo].[DM_Schedule_Allocation] (
    [Sr#No]               FLOAT (53)     NULL,
    [Acquisition Deal No] FLOAT (53)     NULL,
    [Title]               NVARCHAR (255) NULL,
    [Start Date]          DATETIME       NULL,
    [End Date]            DATETIME       NULL,
    [SET India]           FLOAT (53)     NULL,
    [MAX India]           FLOAT (53)     NULL,
    [MAX2]                FLOAT (53)     NULL,
    [SET ME]              FLOAT (53)     NULL,
    [MAX Middle East]     FLOAT (53)     NULL,
    [SET International]   FLOAT (53)     NULL,
    [MAX International]   FLOAT (53)     NULL,
    [SAB International]   FLOAT (53)     NULL,
    [SET Africa]          FLOAT (53)     NULL,
    [MAX Africa]          FLOAT (53)     NULL,
    [SET HD Canada]       FLOAT (53)     NULL,
    [MAX Canada]          FLOAT (53)     NULL,
    [SET United Kingdom]  FLOAT (53)     NULL,
    [MAX United Kingdom]  FLOAT (53)     NULL,
    [SAB United Kingdom]  FLOAT (53)     NULL,
    [SET United States]   FLOAT (53)     NULL,
    [MAX United States]   FLOAT (53)     NULL,
    [SAB US]              FLOAT (53)     NULL,
    [SET HD]              FLOAT (53)     NULL,
    [SET HD US]           FLOAT (53)     NULL,
    [AXN INDIA]           FLOAT (53)     NULL,
    [AXN HD]              FLOAT (53)     NULL,
    [PIX INDIA]           FLOAT (53)     NULL,
    [PIX HD]              FLOAT (53)     NULL
);

