CREATE TABLE [dbo].[MHCueSheetSong] (
    [MHCueSheetSongCode]  BIGINT         IDENTITY (1, 1) NOT NULL,
    [MHCueSheetCode]      INT            NULL,
    [TitleName]           NVARCHAR (400) NULL,
    [EpisodeNo]           INT            NULL,
    [MusicTrackName]      NVARCHAR (400) NULL,
    [FromTime]            TIME (7)       NULL,
    [FromFrame]           INT            NULL,
    [ToTime]              TIME (7)       NULL,
    [ToFrame]             INT            NULL,
    [DurationTime]        TIME (7)       NULL,
    [DurationFrame]       INT            NULL,
    [ExcelLineNo]         INT            NULL,
    [RecordStatus]        CHAR (1)       NULL,
    [ErrorMessage]        VARCHAR (4000) NULL,
    [TitleCode]           INT            NULL,
    [TitleContentCode]    INT            NULL,
    [MusicTitleCode]      INT            NULL,
    [IsApprove]           CHAR (1)       NULL,
    [SongType]            NVARCHAR (200) NULL,
    [MHRequestCode]       BIGINT         NULL,
    [MHMusicSongTypeCode] INT            NULL,
    [MovieAlbumCode]      INT            NULL,
    [MovieAlbum]          NVARCHAR (800) NULL,
    CONSTRAINT [PK_MHCueSheetSong] PRIMARY KEY CLUSTERED ([MHCueSheetSongCode] ASC),
    CONSTRAINT [FK_MHCueSheetSong_MHCueSheet] FOREIGN KEY ([MHCueSheetCode]) REFERENCES [dbo].[MHCueSheet] ([MHCueSheetCode]),
    CONSTRAINT [FK_MHCueSheetSong_Music_Title] FOREIGN KEY ([MusicTitleCode]) REFERENCES [dbo].[Music_Title] ([Music_Title_Code]),
    CONSTRAINT [FK_MHCueSheetSong_Title] FOREIGN KEY ([TitleCode]) REFERENCES [dbo].[Title] ([Title_Code]),
    CONSTRAINT [FK_MHCueSheetSong_Title_Content] FOREIGN KEY ([TitleContentCode]) REFERENCES [dbo].[Title_Content] ([Title_Content_Code]),
    CONSTRAINT [FK_MHRequestCode] FOREIGN KEY ([MHRequestCode]) REFERENCES [dbo].[MHRequest] ([MHRequestCode]),
    CONSTRAINT [FK_MovieAlbumCode] FOREIGN KEY ([MovieAlbumCode]) REFERENCES [dbo].[Music_Album] ([Music_Album_Code])
);

