CREATE TABLE [dbo].[MHRequestDetails] (
    [MHRequestDetailsCode] BIGINT          IDENTITY (1, 1) NOT NULL,
    [MHRequestCode]        BIGINT          NULL,
    [TitleName]            NVARCHAR (400)  NULL,
    [LanguageCode]         INT             NULL,
    [MusicTrackName]       NVARCHAR (400)  NULL,
    [MusicLabelName]       NVARCHAR (400)  NULL,
    [MovieAlbum]           CHAR (1)        NULL,
    [CreateMap]            CHAR (1)        NULL,
    [ActionUserCode]       INT             NULL,
    [TitleCode]            INT             NULL,
    [MusicTitleCode]       INT             NULL,
    [MusicLabelCode]       INT             NULL,
    [MovieAlbumCode]       INT             NULL,
    [IsValid]              CHAR (1)        CONSTRAINT [DF_MHRequestDetails_IsValid] DEFAULT ('P') NULL,
    [IsApprove]            CHAR (1)        CONSTRAINT [DF_MHRequestDetails_IsApprove] DEFAULT ('P') NULL,
    [Remarks]              NVARCHAR (4000) NULL,
    [ValidationMessage]    NVARCHAR (100)  NULL,
    [Singers]              NVARCHAR (MAX)  NULL,
    [StarCasts]            NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_MHRequestDetails] PRIMARY KEY CLUSTERED ([MHRequestDetailsCode] ASC),
    CONSTRAINT [FK_MHRequestDetails_Language] FOREIGN KEY ([LanguageCode]) REFERENCES [dbo].[Language] ([Language_Code]),
    CONSTRAINT [FK_MHRequestDetails_MHRequest] FOREIGN KEY ([MHRequestCode]) REFERENCES [dbo].[MHRequest] ([MHRequestCode]),
    CONSTRAINT [FK_MHRequestDetails_Music_Album] FOREIGN KEY ([MovieAlbumCode]) REFERENCES [dbo].[Music_Album] ([Music_Album_Code]),
    CONSTRAINT [FK_MHRequestDetails_Music_Label] FOREIGN KEY ([MusicLabelCode]) REFERENCES [dbo].[Music_Label] ([Music_Label_Code]),
    CONSTRAINT [FK_MHRequestDetails_Music_Title] FOREIGN KEY ([MusicTitleCode]) REFERENCES [dbo].[Music_Title] ([Music_Title_Code]),
    CONSTRAINT [FK_MHRequestDetails_Title] FOREIGN KEY ([TitleCode]) REFERENCES [dbo].[Title] ([Title_Code])
);

