CREATE TABLE [dbo].[Music_Usage_Report] (
    [Music_Usage_Report_Code] INT             IDENTITY (1, 1) NOT NULL,
    [Title_Names]             NVARCHAR (MAX)  NULL,
    [Title_Code]              NVARCHAR (1000) NULL,
    [Channel]                 NVARCHAR (1000) NULL,
    [Start_Date]              NVARCHAR (1000) NULL,
    [End_Date]                NVARCHAR (1000) NULL,
    [Title_Type]              NVARCHAR (1000) NULL,
    [Genre]                   NVARCHAR (1000) NULL,
    [Music_Label]             NVARCHAR (1000) NULL,
    [StarCast]                NVARCHAR (1000) NULL,
    [starcast_Names]          NVARCHAR (MAX)  NULL,
    [Theme]                   NVARCHAR (1000) NULL,
    [BUCode]                  INT             NULL,
    [Episode_From]            INT             NULL,
    [Episode_To]              INT             NULL,
    [Date_Format]             NVARCHAR (1000) NULL,
    [DateTime_Format]         NVARCHAR (1000) NULL,
    [Created_By]              NVARCHAR (1000) NULL,
    [SysLanguageCode]         INT             NULL,
    [Report_Name]             NVARCHAR (1000) NULL,
    [Expiry_Days]             INT             NULL,
    [Accessibility]           INT             NULL,
    [File_Name]               NVARCHAR (1000) NULL,
    [Process_Start]           DATETIME        NULL,
    [Process_End]             DATETIME        NULL,
    [Report_Status]           CHAR (1)        NULL,
    [Error_Message]           NVARCHAR (MAX)  NULL,
    [Generated_By]            INT             NULL,
    [Generated_On]            DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([Music_Usage_Report_Code] ASC)
);

