CREATE TABLE [dbo].[Notifications] (
    [NotificationsCode]  BIGINT          IDENTITY (1, 1) NOT NULL,
    [NotificationType]   NVARCHAR (MAX)  NULL,
    [EventCategory]      NVARCHAR (MAX)  NULL,
    [UserCode]           BIGINT          NOT NULL,
    [TransType]          BIGINT          NULL,
    [TransCode]          BIGINT          NULL,
    [Email]              NVARCHAR (MAX)  NULL,
    [Mobile]             NVARCHAR (MAX)  NULL,
    [IsSend]             BIT             NOT NULL,
    [IsRead]             BIT             NOT NULL,
    [CC]                 NVARCHAR (MAX)  NULL,
    [BCC]                NVARCHAR (MAX)  NULL,
    [Subject]            NVARCHAR (1000) NULL,
    [HtmlBody]           NVARCHAR (MAX)  NULL,
    [TextBody]           NVARCHAR (MAX)  NULL,
    [ScheduleDateTime]   DATETIME        NULL,
    [NoOfRetry]          INT             NULL,
    [MsgStatusCode]      INT             NULL,
    [SentOrReadDateTime] DATETIME        NULL,
    [API_Status]         NVARCHAR (1000) NULL,
    [ErrorDetails]       NVARCHAR (MAX)  NULL,
    [CreatedOn]          DATETIME        NULL,
    [CreatedBy]          BIGINT          NULL,
    [ModifiedOn]         DATETIME        NULL,
    [ModifiedBy]         BIGINT          NULL,
    [IsAutoEscalated]    BIT             NOT NULL,
    [IsReminderMail]     BIT             NOT NULL,
    [Service_Response]   NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_NF_T_NOTIFICATION_DTLS] PRIMARY KEY CLUSTERED ([NotificationsCode] ASC)
);

