CREATE PROCEDURE [dbo].[USP_Validate_SYN_YEARWISE_RIGHT_FOR_RUN]
	@SYN_DEAL_CODE INT,
	@SYN_DEAL_RUN_CODE INT,
	@TITLE_CODE VARCHAR(1000),
	@MIN_YEARWISE_START_DATE DATETIME,
	@MAX_YEARWISE_END_DATE DATETIME
AS
-- =============================================
-- Author:		Rajesh Godse
-- Create DATE: 24 Feb 2015
-- Description:	Validating Yearwise Run definition for selected titles in Add/Edit run defition page 
-- =============================================
BEGIN
	
	DECLARE @Selected_Deal_Type_Code INT ,@Deal_Type_Condition VARCHAR(MAX) = ''
	SELECT TOP 1 @Selected_Deal_Type_Code = Deal_Type_Code FROM Syn_Deal WHERE Syn_Deal_Code = @SYN_DEAL_CODE
	SELECT @Deal_Type_Condition = dbo.UFN_GetDealTypeCondition(@Selected_Deal_Type_Code)

	IF(   (select count(number) from  dbo.fn_Split_withdelemiter(@TITLE_CODE,',')) > 1)
	BEGIN
		SELECT DISTINCT 
		DBO.UFN_GetTitleNameInFormat(@Deal_Type_Condition, T.Title_Name, ADRT.Episode_From, ADRT.Episode_To) AS Title_Name
		,ADR.RIGHT_START_DATE as [Rights_Start_Date]
		,ADR.RIGHT_END_DATE as [Rights_End_Date] 
		,'' as [CHANNEL_NAME]
		FROM Syn_DEAL_RUN ADRR
		INNER JOIN Syn_Deal_Movie ADM ON ADM.Syn_Deal_Code = @SYN_DEAL_CODE
		INNER JOIN Syn_DEAL_RUN_YEARWISE_RUN  ADYR ON ADYR.Syn_DEAL_RUN_CODE = ADRR.Syn_DEAL_RUN_CODE
		INNER JOIN  Syn_DEAL_RIGHTS ADR ON ADR.Syn_DEAL_CODE = ADRR.Syn_DEAL_CODE
		INNER JOIN  Syn_DEAL_RIGHTS_TITLE ADRT ON ADRT.Syn_DEAL_RIGHTS_CODE = ADR.Syn_DEAL_RIGHTS_CODE AND
		ADRT.Episode_From = ADM.Episode_From AND ADRT.Episode_To = ADM.Episode_End_To AND ADRT.Title_Code = ADM.Title_Code
		INNER JOIN  TITLE T ON T.Title_Code = ADRT.Title_Code
		WHERE ADRR.Syn_DEAL_CODE IN( @SYN_DEAL_CODE)
			AND ADRR.Syn_Deal_Run_Code not in (@SYN_DEAL_RUN_CODE)
			AND ((ADRT.TITLE_CODE IN (SELECT NUMBER FROM DBO.FN_SPLIT_WITHDELEMITER(@TITLE_CODE,',')) AND @Deal_Type_Condition != 'DEAL_PROGRAM') OR
			(ADM.Syn_Deal_Movie_Code IN  (SELECT NUMBER FROM DBO.FN_SPLIT_WITHDELEMITER(@TITLE_CODE,',')) AND @Deal_Type_Condition = 'DEAL_PROGRAM'))
			AND ( 
					(
							(CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) BETWEEN CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103) AND CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103))
							AND
							(CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103) NOT BETWEEN CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103) AND CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103))
						)
						OR
						(
							 (CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103) BETWEEN CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103) AND CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103))
							 AND
							 (CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) NOT BETWEEN CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103) AND CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103))					 
						)
						OR
						(
							 (CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103) BETWEEN CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103) AND CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103))
							 AND
							 (CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) BETWEEN CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103) AND CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103))					 
						)				
						OR
						(
							(CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103) BETWEEN CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) AND CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103))
							AND
							(CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103) NOT BETWEEN CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) AND CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103))
						)
						OR
						(
							(CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103) BETWEEN CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) AND CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103))
							AND
							(CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103) NOT BETWEEN CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) AND CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103))
						)
						OR
						(
							(CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103) BETWEEN CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) AND CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103))
							AND
							(CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103) BETWEEN CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) AND CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103))
						)
				)
	END
	ELSE
	BEGIN

			SELECT DISTINCT T.Title_Name as [Title_Name]
							,ADR.RIGHT_START_DATE as [Rights_Start_Date]
							,ADR.RIGHT_END_DATE as [Rights_End_Date] 
							,'' as [CHANNEL_NAME]
							FROM Syn_DEAL_RUN ADRR

			INNER JOIN Syn_DEAL_RUN_YEARWISE_RUN  ADYR ON ADYR.Syn_DEAL_RUN_CODE = ADRR.Syn_DEAL_RUN_CODE
			INNER JOIN  Syn_DEAL_RIGHTS ADR ON ADR.Syn_DEAL_CODE = ADRR.Syn_DEAL_CODE
			INNER JOIN  Syn_DEAL_RIGHTS_TITLE ADRT ON ADRT.Syn_DEAL_RIGHTS_CODE = ADR.Syn_DEAL_RIGHTS_CODE
			INNER JOIN  TITLE T ON T.Title_Code = ADRT.Title_Code
			where ADR.Syn_Deal_Code = 0
	END

END