CREATE PROCEDURE [dbo].[USP_Validate_YEARWISE_RIGHT_FOR_RUN]
	@ACQ_DEAL_CODE INT,
	@ACQ_DEAL_RUN_CODE INT,
	@TITLE_CODE VARCHAR(1000),
	@MIN_YEARWISE_START_DATE DATETIME,
	@MAX_YEARWISE_END_DATE DATETIME
AS
-- =============================================
-- Author:		Bhavesh Desai
-- Create DATE: 31-October-2014
-- Description:	Validating Yearwise Run definition for selected titles in Add/Edit run defition page 
-- =============================================
BEGIN
	Declare @Loglevel int
	select @Loglevel = Parameter_Value from System_Parameter_New where Parameter_Name='loglevel'
	if(@Loglevel< 2)Exec [USPLogSQLSteps] '[USP_Validate_YEARWISE_RIGHT_FOR_RUN]', 'Step 1', 0, 'Started Procedure', 0, ''
		--SELECT @ACQ_DEAL_CODE = 0, @ACQ_DEAL_RUN_CODE = 0, @TITLE_CODE = '', @MIN_YEARWISE_START_DATE = '', @MAX_YEARWISE_END_DATE = ''

		DECLARE @Selected_Deal_Type_Code INT ,@Deal_Type_Condition VARCHAR(MAX) = ''
		SELECT TOP 1 @Selected_Deal_Type_Code = Deal_Type_Code FROM Acq_Deal (NOLOCK) WHERE Acq_Deal_Code = @ACQ_DEAL_CODE
		SELECT @Deal_Type_Condition = dbo.UFN_GetDealTypeCondition(@Selected_Deal_Type_Code)

		IF(   (select count(number) from  dbo.fn_Split_withdelemiter(@TITLE_CODE,',')) > 1)
		BEGIN
			SELECT DISTINCT 
			DBO.UFN_GetTitleNameInFormat(@Deal_Type_Condition, T.Title_Name, ADRT.Episode_From, ADRT.Episode_To) AS Title_Name
			,ADR.RIGHT_START_DATE as [Rights_Start_Date]
			,ADR.RIGHT_END_DATE as [Rights_End_Date] 
			,'' as [CHANNEL_NAME]
			FROM ACQ_DEAL_RUN ADRR (NOLOCK)
			INNER JOIN Acq_Deal_Movie ADM (NOLOCK) ON ADM.Acq_Deal_Code = @ACQ_DEAL_CODE
			INNER JOIN ACQ_DEAL_RUN_YEARWISE_RUN  ADYR (NOLOCK) ON ADYR.ACQ_DEAL_RUN_CODE = ADRR.ACQ_DEAL_RUN_CODE
			INNER JOIN  ACQ_DEAL_RIGHTS ADR (NOLOCK) ON ADR.ACQ_DEAL_CODE = ADRR.ACQ_DEAL_CODE
			INNER JOIN  ACQ_DEAL_RIGHTS_TITLE ADRT (NOLOCK) ON ADRT.ACQ_DEAL_RIGHTS_CODE = ADR.ACQ_DEAL_RIGHTS_CODE AND
			ADRT.Episode_From = ADM.Episode_Starts_From AND ADRT.Episode_To = ADM.Episode_End_To AND ADRT.Title_Code = ADM.Title_Code
			INNER JOIN Acq_Deal_Run_Title ADRNT (NOLOCK) ON ADRT.Episode_From = ADRNT.Episode_From AND ADRT.Episode_To = ADRNT.Episode_To AND ADRT.Title_Code = ADRNT.Title_Code AND ADRR.Acq_Deal_Run_Code = ADRNT.Acq_Deal_Run_Code
			INNER JOIN  TITLE T (NOLOCK) ON T.Title_Code = ADRT.Title_Code
			WHERE ADRR.ACQ_DEAL_CODE IN( @ACQ_DEAL_CODE)
				AND ADRR.Acq_Deal_Run_Code not in (@ACQ_DEAL_RUN_CODE)
				AND ((ADRNT.Title_Code IN (SELECT NUMBER FROM DBO.FN_SPLIT_WITHDELEMITER(@TITLE_CODE,',')) AND @Deal_Type_Condition != 'DEAL_PROGRAM') OR
				(ADM.Acq_Deal_Movie_Code IN  (SELECT NUMBER FROM DBO.FN_SPLIT_WITHDELEMITER(@TITLE_CODE,',')) AND @Deal_Type_Condition = 'DEAL_PROGRAM'))
				AND ( 
						(
								(CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) BETWEEN CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103) AND CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103))
								AND
								(CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103) NOT BETWEEN CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103) AND CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103))
							)
							OR
							(
								 (CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103) BETWEEN CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103) AND CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103))
								 AND
								 (CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) NOT BETWEEN CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103) AND CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103))					 
							)
							OR
							(
								 (CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103) BETWEEN CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103) AND CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103))
								 AND
								 (CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) BETWEEN CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103) AND CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103))					 
							)				
							OR
							(
								(CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103) BETWEEN CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) AND CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103))
								AND
								(CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103) NOT BETWEEN CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) AND CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103))
							)
							OR
							(
								(CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103) BETWEEN CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) AND CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103))
								AND
								(CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103) NOT BETWEEN CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) AND CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103))
							)
							OR
							(
								(CONVERT(DATETIME, ADR.RIGHT_END_DATE, 103) BETWEEN CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) AND CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103))
								AND
								(CONVERT(DATETIME, ADR.RIGHT_START_DATE, 103) BETWEEN CONVERT(DATETIME, @MIN_YEARWISE_START_DATE, 103) AND CONVERT(DATETIME, @MAX_YEARWISE_END_DATE, 103))
							)
					)
		END
		ELSE
		BEGIN

				SELECT DISTINCT T.Title_Name as [Title_Name]
								,ADR.RIGHT_START_DATE as [Rights_Start_Date]
								,ADR.RIGHT_END_DATE as [Rights_End_Date] 
								,'' as [CHANNEL_NAME]
								FROM ACQ_DEAL_RUN ADRR (NOLOCK)

				INNER JOIN ACQ_DEAL_RUN_YEARWISE_RUN  ADYR (NOLOCK) ON ADYR.ACQ_DEAL_RUN_CODE = ADRR.ACQ_DEAL_RUN_CODE
				INNER JOIN  ACQ_DEAL_RIGHTS ADR (NOLOCK) ON ADR.ACQ_DEAL_CODE = ADRR.ACQ_DEAL_CODE
				INNER JOIN  ACQ_DEAL_RIGHTS_TITLE ADRT  (NOLOCK) ON ADRT.ACQ_DEAL_RIGHTS_CODE = ADR.ACQ_DEAL_RIGHTS_CODE
				INNER JOIN  TITLE T  (NOLOCK) ON T.Title_Code = ADRT.Title_Code
				where ADR.Acq_Deal_Code = 0
		END
	
	if(@Loglevel< 2)Exec [USPLogSQLSteps] '[USP_Validate_YEARWISE_RIGHT_FOR_RUN]', 'Step 2', 0, 'Procedure Excution Completed', 0, ''
END
