ALTER PROCEDURE [dbo].[USPAPI_List_Acq]
	@StrSearch NVARCHAR(Max)=NULL,
	@PageNo Int=1,
	@OrderByCndition Varchar(100)='Acq_Deal_Code desc',
	@IsPaging Varchar(2)='Y',
	@PageSize Int=50,
	@RecordCount Int Out,
	@User_Code INT=143,
	@ExactMatch varchar(max) = ''
AS
BEGIN
Declare @Loglevel int;
	select @Loglevel = Parameter_Value from System_Parameter_New where Parameter_Name='loglevel'
	if(@Loglevel< 2)Exec [USPLogSQLSteps] '[USPAPI_List_Acq]', 'Step 1', 0, 'Started Procedure', 0, '' 
	
	DECLARE @Temp_Acq_List as TABLE(Acq_Deal_Code INT,Agreement_No VARCHAR,version VARCHAR,Deal_Type_Code INT,contentType VARCHAR,VendorName VARCHAR,DealSignedDate DATETIME,DealDesc VARCHAR,Remarks VARCHAR,DealTitles VARCHAR,RightPeriod VARCHAR,CountryDetails VARCHAR,IsZeroWorkFlow VARCHAR,dealWorkFlowStatus VARCHAR,Final_Deal_Workflow_Status VARCHAR,status VARCHAR,isActive VARCHAR,Show_Hide_Buttons VARCHAR,AT_Status VARCHAR,Cnt_DealTitles INT,[Previous Version] VARCHAR);

	CREATE TABLE #Temp_Acq_List
	(
		TotalMilestoneCount INT,
		VendorName NVARCHAR(MAX),
		Acq_Deal_Code INT,
		Agreement_No VARCHAR(50),
		Deal_Type_Code INT,
		currentApproverCode INT,
		WorkFlowDetailsCount INT,
		CountryDetails NVARCHAR(MAX),
		RightPeriod NVARCHAR(MAX),
		DealTitles NVARCHAR(MAX),
		Cnt_DealTitles INT,
		IsShowReopenBtn VARCHAR(2),
		IsCountMovieClosed INT,
		IsShowDealMovieCloseBtn INT,
		isShowAmmendmentBtn INT,
		DealTagDescription NVARCHAR(MAX),
		DealTypeName NVARCHAR(100),
		IntCode INT,
		LastUpdatedTime DATETIME,
		LastActionBy INT,
		IsCompleted VARCHAR(2),
		IsZeroWorkFlow VARCHAR(2),
		attachWorkflow VARCHAR(2),
		dealWorkFlowStatus NVARCHAR(10),
		DealNo VARCHAR(50),
		IsAutoGenerated VARCHAR(2),
		DealSignedDate DATETIME,
		parentDealCode INT,
		DealDesc NVARCHAR(MAX),
		isReleased VARCHAR(2),
		IsTerminate VARCHAR(10),
		IsTentative VARCHAR(10),
		IsDealContinue VARCHAR(10),
		version VARCHAR(50),
		Previous_Version VARCHAR(50),
		work_flow_code INT,
		workflowcode INT,
		DealTagCode INT,
		isActive VARCHAR(1),
		contentType VARCHAR(100),
		currencyCode INT,
		insertedOn DATETIME,
		insertedBy INT,
		customerContactCode INT,
		categoryCode INT,
		customerCode INT,
		EntityCode INT,
		YearType CHAR(2),
		refNo NVARCHAR(200),
		exchangeRate numeric,
		PaymentTermsNConditions NVARCHAR(max),
		Validate_CostWith_Budget VARCHAR(2),
		BudgetWise_Costing_Applicable VARCHAR(2),
		DealAMDDate DATETIME,
		Status VARCHAR(10),
		AT_Status VARCHAR(10),
		DealFor INT,
		Remarks NVARCHAR(MAX),
		Deal_Complete_Flag NVARCHAR(10),
		MasterDealMovieCodeToLink INT,
		Business_Unit_Code INT,
		Business_Unit_Name VARCHAR(100),
		Last_Updated_Time DATETIME,
		Final_Deal_Workflow_Status VARCHAR(100),
		Show_Hide_Buttons VARCHAR(100),
		Row_Num INT
	)

	INSERT INTO #Temp_Acq_List
	EXECUTE [USP_List_Acq] @StrSearch,@PageNo,@OrderByCndition,@IsPaging,@PageSize,@RecordCount OUT,@User_Code,@ExactMatch
	
	select * from #Temp_Acq_List

	if(@Loglevel< 2)Exec [USPLogSQLSteps] '[USPAPI_List_Acq]', 'Step 2', 0, 'Procedure Excuting Completed', 0, '' 

END
