//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class AL_Vendor_Details
    {
        [JsonIgnore]
        public State EntityState { get; set; }
        [JsonProperty(Order = -1)]
        public int AL_Vendor_Detail_Code { get; set; }
        [JsonProperty(Order = 1)]
        public Nullable<int> Vendor_Code { get; set; }
        [JsonProperty(Order = 2)]
        public string Banner_Codes { get; set; }
        [JsonProperty(Order = 3)]
        public string Pref_Exclusion_Codes { get; set; }
        [JsonProperty(Order = 4)]
        public Nullable<int> Extended_Group_Code_Booking { get; set; }

        [JsonIgnore]
        public virtual Vendor Vendor { get; set; }
        [JsonIgnore]
        public virtual Extended_Group Extended_Group { get; set; }
    }
}
