//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Alternate_Config
    {
        public Alternate_Config()
        {
            this.Title_Alternate = new HashSet<Title_Alternate>();
            this.Title_Alternate_Content = new HashSet<Title_Alternate_Content>();
        }

        public State EntityState { get; set; }
        public int Alternate_Config_Code { get; set; }
        public string Alternate_Name { get; set; }
        public Nullable<int> Language_Code { get; set; }
        public Nullable<int> Display_Order { get; set; }
        public string Direction { get; set; }
        public string Is_Active { get; set; }

        public virtual ICollection<Title_Alternate> Title_Alternate { get; set; }
        public virtual ICollection<Title_Alternate_Content> Title_Alternate_Content { get; set; }
    }
}
