//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class BVException_Users
    {
        public int Bv_Exception_Users_Code { get; set; }
        [JsonIgnore]
        public State EntityState { get; set; }
        public int Bv_Exception_Code { get; set; }
        public int Users_Code { get; set; }
    
        public virtual BVException BVException { get; set; }
        [JsonIgnore]
        public virtual User User { get; set; }
    }
}
