//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Country
    {
        public Country()
        {
            this.Acq_Deal_Rights_Blackout_Territory = new HashSet<Acq_Deal_Rights_Blackout_Territory>();
            this.Acq_Deal_Rights_Holdback_Territory = new HashSet<Acq_Deal_Rights_Holdback_Territory>();
            this.Acq_Deal_Pushback_Territory = new HashSet<Acq_Deal_Pushback_Territory>();
            this.Acq_Deal_Rights_Territory = new HashSet<Acq_Deal_Rights_Territory>();
            this.Channel_Territory = new HashSet<Channel_Territory>();
            this.Country_Language = new HashSet<Country_Language>();
            this.Syn_Deal_Rights_Blackout_Territory = new HashSet<Syn_Deal_Rights_Blackout_Territory>();
            this.Syn_Deal_Rights_Holdback_Territory = new HashSet<Syn_Deal_Rights_Holdback_Territory>();
            this.Syn_Deal_Rights_Territory = new HashSet<Syn_Deal_Rights_Territory>();
            this.Territory_Details = new HashSet<Territory_Details>();
            this.Title_Country = new HashSet<Title_Country>();
            this.Vendor_Country = new HashSet<Vendor_Country>();
            this.Avail_Acq = new HashSet<Avail_Acq>();
            this.IPR_REP = new HashSet<IPR_REP>();
            this.Music_Deal_Country = new HashSet<Music_Deal_Country>();
            this.Report_Territory_Country = new HashSet<Report_Territory_Country>();
            this.Title_Alternate_Country = new HashSet<Title_Alternate_Country>();

        }

        [JsonIgnore]
        public State EntityState { get; set; }
        [JsonProperty(Order = -1)]
        public int Country_Code { get; set; }
        [JsonProperty(Order = 1)]
        public string Country_Name { get; set; }
        [JsonProperty(Order = 2)]
        public string Is_Domestic_Territory { get; set; }
        [JsonProperty(Order = 3)]
        public string Is_Theatrical_Territory { get; set; }
        [JsonProperty(Order = 4)]
        public string Is_Ref_Acq { get; set; }
        [JsonProperty(Order = 5)]
        public string Is_Ref_Syn { get; set; }
        [JsonIgnore]
        public Nullable<int> Parent_Country_Code { get; set; }
        [NotMapped]
        [JsonProperty(Order = 6)]
        public string Parent_Country_Name { get; set; }
        [JsonProperty(Order = 7)]
        public string Applicable_For_Asrun_Schedule { get; set; }
        [JsonProperty(Order = 8)]
        public System.DateTime Inserted_On { get; set; }
        [JsonIgnore]
        public int Inserted_By { get; set; }
        [NotMapped]
        [JsonProperty(Order = 9)]
        public string Inserted_By_User { get; set; }
        [JsonIgnore]
        public Nullable<System.DateTime> Lock_Time { get; set; }
        [JsonProperty(Order = 10)]
        public Nullable<System.DateTime> Last_Updated_Time { get; set; }
        [JsonIgnore]
        public Nullable<int> Last_Action_By { get; set; }
        [NotMapped]
        [JsonProperty(Order = 11)]
        public string Last_Action_By_User { get; set; }
        [JsonProperty(Order = 12)]
        public string Is_Active { get; set; }
        [JsonProperty(Order = 13)]
        public int Base_Country_Count { get; set; }

        [JsonIgnore]
        public virtual ICollection<Acq_Deal_Rights_Blackout_Territory> Acq_Deal_Rights_Blackout_Territory { get; set; }
        [JsonIgnore]
        public virtual ICollection<Acq_Deal_Rights_Holdback_Territory> Acq_Deal_Rights_Holdback_Territory { get; set; }
        [JsonIgnore]
        public virtual ICollection<Acq_Deal_Rights_Territory> Acq_Deal_Rights_Territory { get; set; }
        [JsonIgnore]
        public virtual ICollection<Channel_Territory> Channel_Territory { get; set; }
        [JsonIgnore]
        public virtual ICollection<Country_Language> Country_Language { get; set; }
        [JsonIgnore]
        public virtual ICollection<Syn_Deal_Rights_Blackout_Territory> Syn_Deal_Rights_Blackout_Territory { get; set; }
        [JsonIgnore]
        public virtual ICollection<Syn_Deal_Rights_Holdback_Territory> Syn_Deal_Rights_Holdback_Territory { get; set; }
        [JsonIgnore]
        public virtual ICollection<Syn_Deal_Rights_Territory> Syn_Deal_Rights_Territory { get; set; }
        [JsonIgnore]
        public virtual ICollection<Territory_Details> Territory_Details { get; set; }
        [JsonIgnore]
        public virtual ICollection<Title_Country> Title_Country { get; set; }
        [JsonIgnore]
        public virtual ICollection<Vendor_Country> Vendor_Country { get; set; }
        [JsonIgnore]
        public virtual ICollection<Acq_Deal_Pushback_Territory> Acq_Deal_Pushback_Territory { get; set; }
        [JsonIgnore]
        public virtual ICollection<Avail_Acq> Avail_Acq { get; set; }
        [JsonIgnore]
        public virtual ICollection<IPR_REP> IPR_REP { get; set; }
        [JsonIgnore]
        public virtual ICollection<Music_Deal_Country> Music_Deal_Country { get; set; }
        [JsonIgnore]
        public virtual ICollection<Report_Territory_Country> Report_Territory_Country { get; set; }
        [JsonIgnore]
        public virtual ICollection<Title_Alternate_Country> Title_Alternate_Country { get; set; }

    }
}
