//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Country_Language
    {
        public State EntityState { get; set; }
        public int Country_Language_Code { get; set; }
        public Nullable<int> Country_Code { get; set; }
        public Nullable<int> Language_Code { get; set; }

        [JsonIgnore]
        public virtual Country Country { get; set; }
        [JsonIgnore]
        public virtual Language Language { get; set; }
    }
}
