//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Currency
    {
        public Currency()
        {
            this.Acq_Deal = new HashSet<Acq_Deal>();
            this.Currency_Exchange_Rate = new HashSet<Currency_Exchange_Rate>();
            this.Material_Order_Details = new HashSet<Material_Order_Details>();
            this.Syn_Deal = new HashSet<Syn_Deal>();
            this.Acq_Deal_Cost = new HashSet<Acq_Deal_Cost>();
            this.Syn_Deal_Revenue = new HashSet<Syn_Deal_Revenue>();
        }

        [JsonIgnore]
        public State EntityState { get; set; }
        [JsonProperty(Order = -1)]
        public int Currency_Code { get; set; }
        [JsonProperty(Order = 1)]
        public string Currency_Name { get; set; }
        [JsonProperty(Order = 2)]
        public string Currency_Sign { get; set; }
        [JsonProperty(Order = 3)]
        public System.DateTime Inserted_On { get; set; }
        [JsonIgnore]
        public int Inserted_By { get; set; }
        [NotMapped]
        [JsonProperty(Order = 4)]
        public string Inserted_By_User { get; set; }
        [JsonIgnore]
        public Nullable<System.DateTime> Lock_Time { get; set; }
        [JsonProperty(Order = 5)]
        public Nullable<System.DateTime> Last_Updated_Time { get; set; }
        [JsonIgnore]
        public Nullable<int> Last_Action_By { get; set; }
        [NotMapped]
        [JsonProperty(Order = 6)]
        public string Last_Action_By_User { get; set; }
        [JsonProperty(Order = 7)]
        public string Is_Active { get; set; }
        [JsonProperty(Order = 8)]
        public string Is_Base_Currency { get; set; }

        [JsonIgnore]
        public virtual ICollection<Acq_Deal> Acq_Deal { get; set; }
        [JsonProperty(Order = 9)]
        public virtual ICollection<Currency_Exchange_Rate> Currency_Exchange_Rate { get; set; }
        [JsonIgnore]
        public virtual ICollection<Material_Order_Details> Material_Order_Details { get; set; }
        [JsonIgnore]
        public virtual ICollection<Syn_Deal> Syn_Deal { get; set; }
        [JsonIgnore]
        public virtual ICollection<Acq_Deal_Cost> Acq_Deal_Cost { get; set; }
        [JsonIgnore]
        public virtual ICollection<Syn_Deal_Revenue> Syn_Deal_Revenue { get; set; }    

    }
}
