//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_Notification_Msg
    {
        public int Email_Notification_Msg_Code { get; set; }
        public string Email_Msg { get; set; }
        public string Type { get; set; }
        public string Email_Msg_For { get; set; }
    }
}
