//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_Config
    {
        public Email_Config()
        {
            this.Email_Config_Detail = new HashSet<Email_Config_Detail>();
        }
    
    	public State EntityState { get; set; }
        public int Email_Config_Code { get; set; }
    	public string Email_Type { get; set; }
    	public string OnScreen_Notification { get; set; }
    	public string Allow_Config { get; set; }
    	public string IsChannel { get; set; }
    	public string IsBusinessUnit { get; set; }
    	public string Notification_Frequency { get; set; }
    	public string Days_Config { get; set; }
    	public string Days_Freq { get; set; }
    	public string Remarks { get; set; }
        public string User_Count { get; set; }
        public Nullable<int> Inserted_By { get; set; }
        public Nullable<System.DateTime> Inserted_On { get; set; }
        public Nullable<int> Last_Updated_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_On { get; set; }
        public int Count { get; set; }
        public int TotalCount { get; set; }
        public string Event_Type { get; set; }
        public virtual ICollection<Email_Config_Detail> Email_Config_Detail { get; set; }
        public virtual ICollection<Email_Notification_Log> Email_Notification_Log { get; set; }
    }
}
