//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error_Code_Master
    {
        public int Error_Code { get; set; }
        public string Upload_Error_Code { get; set; }
        public string Error_Description { get; set; }
        public string Error_For { get; set; }
    }
}
