//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Genre
    {
        public Genre()
        {
            this.Channels = new HashSet<Channel>();
            this.Title_Geners = new HashSet<Title_Geners>();
            this.Programs = new HashSet<Program>();
            this.Title_Alternate_Genres = new HashSet<Title_Alternate_Genres>();
        }

        [JsonIgnore]
        public State EntityState { get; set; }
        [JsonProperty(Order = -1)]
        public int Genres_Code { get; set; }
        [JsonProperty(Order = 1)]
        public string Genres_Name { get; set; }
        [JsonProperty(Order = 2)]
        public Nullable<System.DateTime> Inserted_On { get; set; }
        [JsonIgnore]
        public Nullable<int> Inserted_By { get; set; }
        [NotMapped]
        [JsonProperty(Order = 3)]
        public string Inserted_By_User { get; set; }
        [JsonIgnore]
        public Nullable<System.DateTime> Lock_Time { get; set; }
        [JsonProperty(Order = 4)]
        public Nullable<System.DateTime> Last_Updated_Time { get; set; }
        [JsonIgnore]        
        public Nullable<int> Last_Action_By { get; set; }
        [NotMapped]
        [JsonProperty(Order = 5)]
        public string Last_Action_By_User { get; set; }
        [JsonProperty(Order = 6)]
        public string Is_Active { get; set; }

        [JsonIgnore]
        public virtual ICollection<Channel> Channels { get; set; }
        [JsonIgnore]
        public virtual ICollection<Title_Geners> Title_Geners { get; set; }
        [JsonIgnore]
        public virtual ICollection<Program> Programs { get; set; }
        [JsonIgnore]
        public virtual ICollection<Title_Alternate_Genres> Title_Alternate_Genres { get; set; }

    }
}
