//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Language_Group_Details
    {
        public int Language_Group_Details_Code { get; set; }
        [JsonIgnore]
        public State EntityState { get; set; }
        public Nullable<int> Language_Group_Code { get; set; }
        [JsonIgnore]
        public Nullable<int> Language_Code { get; set; }
        [NotMapped]
        public string Language_Name
        {
            get
            {
                return Language.Language_Name;
            }
            set
            {

            }
        }
        [JsonIgnore]
        public virtual Language Language { get; set; }
        [JsonIgnore]
        public virtual Language_Group Language_Group { get; set; }
    }
}
