//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map_Extended_Columns_Details
    {
        public int Map_Extended_Columns_Details_Code { get; set; }
        public Nullable<int> Map_Extended_Columns_Code { get; set; }
        public Nullable<int> Columns_Value_Code { get; set; }
        public State EntityState { get; set; }
        public virtual Extended_Columns_Value Extended_Columns_Value { get; set; }
        public virtual Map_Extended_Columns Map_Extended_Columns { get; set; }
    }
}
