//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module_Status_History
    {
        public State EntityState { get; set; }
        public int Module_Status_Code { get; set; }
        public Nullable<int> Module_Code { get; set; }
        public Nullable<int> Record_Code { get; set; }
        public string Status { get; set; }
        public Nullable<int> Status_Changed_By { get; set; }
        public Nullable<System.DateTime> Status_Changed_On { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Version_No { get; set; }

        public virtual System_Module System_Module { get; set; }
    }
}
