//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monetisation_Type
    {
        public Monetisation_Type()
        {
            this.Acq_Deal_Sport_Monetisation_Ancillary_Type = new HashSet<Acq_Deal_Sport_Monetisation_Ancillary_Type>();
        }
    
    	public State EntityState { get; set; }    public int Monetisation_Type_Code { get; set; }
    	    public string Monetisation_Type_Name { get; set; }
    	    public string Is_Active { get; set; }

            public virtual ICollection<Acq_Deal_Sport_Monetisation_Ancillary_Type> Acq_Deal_Sport_Monetisation_Ancillary_Type { get; set; }
    }
}
