//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Music_Album
    {
        public Music_Album()
        {
            this.Music_Album_Talent = new HashSet<Music_Album_Talent>();
            this.Music_Title = new HashSet<Music_Title>();
            this.MHRequestDetails = new HashSet<MHRequestDetail>();
        }

        public State EntityState { get; set; }    public int Music_Album_Code { get; set; }
        public string Music_Album_Name { get; set; }
        public string Album_Type { get; set; }
        public Nullable<int> Inserted_By { get; set; }
        public Nullable<System.DateTime> Inserted_On { get; set; }
        public Nullable<int> Last_Action_By { get; set; }
        public Nullable<System.DateTime> Last_UpDated_Time { get; set; }
        public string Is_Active { get; set; }

        public virtual ICollection<Music_Album_Talent> Music_Album_Talent { get; set; }
        public virtual ICollection<Music_Title> Music_Title { get; set; }
        public virtual ICollection<MHRequestDetail> MHRequestDetails { get; set; }
    }
}
