//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Music_Theme
    {
        public Music_Theme()
        {
            this.Music_Title_Theme = new HashSet<Music_Title_Theme>();
        }

        public State EntityState { get; set; }    public int Music_Theme_Code { get; set; }
        public string Music_Theme_Name { get; set; }
        public Nullable<System.DateTime> Inserted_On { get; set; }
        public Nullable<int> Inserted_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Time { get; set; }
        public Nullable<int> Last_Action_By { get; set; }
        public string Is_Active { get; set; }

        public virtual ICollection<Music_Title_Theme> Music_Title_Theme { get; set; }
    }
}
