//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music_Type
    {
        public Music_Type()
        {
            this.Music_Title = new HashSet<Music_Title>();
        }
    
    	public State EntityState { get; set; }    public int Music_Type_Code { get; set; }
    	    public string Music_Type_Name { get; set; }
    	    public string Is_Active { get; set; }
            public string Type { get; set; }

            public virtual ICollection<Music_Title> Music_Title { get; set; }
            public virtual ICollection<Music_Title> Music_Title1 { get; set; }
    }
}
