//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Platform_Broadcast
    {
        public State EntityState { get; set; }
        public int Platform_Broadcast_Code { get; set; }
        public Nullable<int> Platform_Code { get; set; }
        public Nullable<int> Broadcast_Mode_Code { get; set; }
    }
}
