//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promoter_Remarks
    {
        public Promoter_Remarks()
        {
            this.Acq_Deal_Rights_Promoter_Remarks = new HashSet<Acq_Deal_Rights_Promoter_Remarks>();
            this.Syn_Deal_Rights_Promoter_Remarks = new HashSet<Syn_Deal_Rights_Promoter_Remarks>();
        }
    
    	public State EntityState { get; set; }    public int Promoter_Remarks_Code { get; set; }
    	    public string Promoter_Remark_Desc { get; set; }
    	    public Nullable<System.DateTime> Inserted_On { get; set; }
    	    public Nullable<int> Inserted_By { get; set; }
    	    public Nullable<System.DateTime> Last_Updated_Time { get; set; }
    	    public Nullable<int> Last_Action_By { get; set; }
    	    public string Is_Active { get; set; }
    
        public virtual ICollection<Acq_Deal_Rights_Promoter_Remarks> Acq_Deal_Rights_Promoter_Remarks { get; set; }
        public virtual ICollection<Syn_Deal_Rights_Promoter_Remarks> Syn_Deal_Rights_Promoter_Remarks { get; set; }
    }
}
