//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provisional_Deal_Run_Channel
    {
    	public State EntityState { get; set; }    public int Provisional_Deal_Run_Channel_Code { get; set; }
    	    public Nullable<int> Provisional_Deal_Run_Code { get; set; }
    	    public Nullable<int> Channel_Code { get; set; }
    	    public Nullable<System.DateTime> Right_Start_Date { get; set; }
    	    public Nullable<System.DateTime> Right_End_Date { get; set; }

            public string _Dummy_Guid { get; set; }
            public string Dummy_Guid
            {
                get
                {
                    if (string.IsNullOrEmpty(_Dummy_Guid))
                        _Dummy_Guid = GetDummy_Guid();
                    return _Dummy_Guid;
                }
            }
            private string GetDummy_Guid()
            {
                return Guid.NewGuid().ToString();
            }

        public virtual Channel Channel { get; set; }
        public virtual Provisional_Deal_Run Provisional_Deal_Run { get; set; }
    }
}
