//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue_Heads
    {
        public int Rev_Hd_Code { get; set; }
        public string Rev_Hd_Name { get; set; }
        public Nullable<int> Rev_Hd_Type { get; set; }
    }
}
