//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Royalty_Recoupment
    {
        public Royalty_Recoupment()
        {
            this.Royalty_Recoupment_Details = new HashSet<Royalty_Recoupment_Details>();
            this.Acq_Deal_Cost = new HashSet<Acq_Deal_Cost>();
            this.Syn_Deal_Revenue = new HashSet<Syn_Deal_Revenue>();
        }

        [JsonIgnore]
        public State EntityState { get; set; }
        [JsonProperty(Order = -1)]
        public int Royalty_Recoupment_Code { get; set; }
        public string Royalty_Recoupment_Name { get; set; }
        public string Is_Active { get; set; }
        public System.DateTime Inserted_On { get; set; }
        [JsonIgnore]
        public int Inserted_By { get; set; }
        [NotMapped]
        public string Inserted_By_User { get; set; }
        [JsonIgnore]
        public Nullable<System.DateTime> Lock_Time { get; set; }
        public Nullable<System.DateTime> Last_Updated_Time { get; set; }
        [JsonIgnore]
        public Nullable<int> Last_Action_By { get; set; }
        [NotMapped]
        public string Last_Action_By_User { get; set; }

        [JsonProperty(Order = 1)]
        public virtual ICollection<Royalty_Recoupment_Details> Royalty_Recoupment_Details { get; set; }
        [JsonIgnore]
        public virtual ICollection<Acq_Deal_Cost> Acq_Deal_Cost { get; set; }
        [JsonIgnore]
        public virtual ICollection<Syn_Deal_Revenue> Syn_Deal_Revenue { get; set; }
    }
}
