//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TATSLA
    {
        public TATSLA()
        {
            this.TATSLAMatrices = new HashSet<TATSLAMatrix>();
        }
    
    	public State EntityState { get; set; }    public int TATSLACode { get; set; }
    	    public string TATSLAName { get; set; }
    	    public Nullable<int> BusinessUnitCode { get; set; }
    	    public Nullable<int> DealTypeCode { get; set; }
    	    public string IsActive { get; set; }
    	    public Nullable<System.DateTime> InsertedOn { get; set; }
    	    public Nullable<int> InsertedBy { get; set; }
    	    public Nullable<System.DateTime> UpdatedOn { get; set; }
    	    public Nullable<int> UpdatedBy { get; set; }
    
        public virtual ICollection<TATSLAMatrix> TATSLAMatrices { get; set; }
    }
}
