//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHouseIdMap
    {
        public int Map_Code { get; set; }
        public string Map_House_Id_Unk { get; set; }
        public string Map_House_Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> Last_Updated_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_On { get; set; }
        public string Src { get; set; }
        public Nullable<int> FileID { get; set; }
    }
}
