//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Title_Objection_Rights_Period
    {
        public State EntityState { get; set; }
        public int Title_Objection_Rights_Period_Code { get; set; }
        public Nullable<int> Title_Objection_Code { get; set; }
        public Nullable<System.DateTime> Rights_Start_Date { get; set; }
        public Nullable<System.DateTime> Rights_End_Date { get; set; }

        public virtual Title_Objection Title_Objection { get; set; }
    }
}
