//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Users_Business_Unit
    {
        [JsonProperty(Order = -1)]
        public int Users_Business_Unit_Code { get; set; }
        [JsonIgnore]
        public State EntityState { get; set; }
        [JsonProperty(Order = 1)]
        public Nullable<int> Users_Code { get; set; }
        [JsonIgnore]
        public Nullable<int> Business_Unit_Code { get; set; }
        [NotMapped]
        [JsonProperty(Order = 2)]
        public string Business_Unit_name { get; set; }
        [JsonIgnore]
        public virtual Business_Unit Business_Unit { get; set; }
        [JsonIgnore]
        public virtual User User { get; set; }
    }
}
