//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Vendor_Role
    {
        public State EntityState { get; set; }
        public int Vendor_Role_Code { get; set; }
        public int Vendor_Code { get; set; }
        public int Role_Code { get; set; }
        public string Is_Active { get; set; }

        public virtual Vendor Vendor { get; set; }
        public virtual Role Role { get; set; }
    }
}
