//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Vendor
    {
        public Vendor()
        {
            this.Acq_Deal = new HashSet<Acq_Deal>();
            this.Acq_Deal_Licensor = new HashSet<Acq_Deal_Licensor>();
            this.Material_Order = new HashSet<Material_Order>();
            this.Syn_Deal = new HashSet<Syn_Deal>();
            this.Vendor_Contacts = new HashSet<Vendor_Contacts>();
            this.Vendor_Country = new HashSet<Vendor_Country>();
            this.Vendor_Role = new HashSet<Vendor_Role>();
            this.Acq_Deal_Cost_Commission = new HashSet<Acq_Deal_Cost_Commission>();
            this.Acq_Deal_Cost_Variable_Cost = new HashSet<Acq_Deal_Cost_Variable_Cost>();
            this.Syn_Deal_Revenue_Commission = new HashSet<Syn_Deal_Revenue_Commission>();
            this.Syn_Deal_Revenue_Variable_Cost = new HashSet<Syn_Deal_Revenue_Variable_Cost>();
            this.Music_Deal = new HashSet<Music_Deal>();
            this.Music_Deal_Vendor = new HashSet<Music_Deal_Vendor>();
            this.Provisional_Deal_Licensor = new HashSet<Provisional_Deal_Licensor>();
            this.MHPlayLists = new HashSet<MHPlayList>();
            this.MHRequests = new HashSet<MHRequest>();
            this.MHCueSheets = new HashSet<MHCueSheet>();
            this.AL_Vendor_Details = new HashSet<AL_Vendor_Details>();
            this.AL_Vendor_OEM = new HashSet<AL_Vendor_OEM>();
            this.AL_Vendor_Rule = new HashSet<AL_Vendor_Rule>();
            this.AL_Vendor_TnC = new HashSet<AL_Vendor_TnC>();
            this.AL_Booking_Sheet = new HashSet<AL_Booking_Sheet>();
            this.AL_Material_Tracking = new HashSet<AL_Material_Tracking>();
        }

        [JsonIgnore]
        public State EntityState { get; set; }
        [JsonProperty(Order = -1)]
        public int Vendor_Code { get; set; }
        public string Vendor_Name { get; set; }
        public string Address { get; set; }
        public string Phone_No { get; set; }
        public string Fax_No { get; set; }
        public string ST_No { get; set; }
        public string VAT_No { get; set; }
        public string TIN_No { get; set; }
        public string PAN_No { get; set; }
        public Nullable<System.DateTime> Inserted_On { get; set; }
        [JsonIgnore]
        public Nullable<int> Inserted_By { get; set; }
        [NotMapped]
        public string Inserted_By_user { get; set; }
        [JsonIgnore]
        public Nullable<System.DateTime> Lock_Time { get; set; }
        public Nullable<System.DateTime> Last_Updated_Time { get; set; }
        [JsonIgnore]
        public Nullable<int> Last_Action_By { get; set; }
        [NotMapped]
        public string Last_Action_By_user { get; set; }
        public string Is_Active { get; set; }
        [JsonIgnore]
        public string Reference_Id_1 { get; set; }
        [JsonIgnore]
        public string Reference_Id_2 { get; set; }
        [JsonIgnore]
        public string Reference_Id_3 { get; set; }
        public string CST_No { get; set; }
        [JsonIgnore]
        public string SAP_Vendor_Code { get; set; }
        public string Is_External { get; set; }
        public string CIN_No { get; set; }
        public string GST_No { get; set; }
        [JsonIgnore]
        public string Is_BV_Push { get; set; }
        public string Short_Code { get; set; }
        public Nullable<int> Ref_Vendor_Key { get; set; }
        public string Record_Status { get; set; }
        public string Error_Description { get; set; }
        [JsonIgnore]
        public Nullable<int> Party_Category_Code { get; set; }
        [NotMapped]
        public string Party_Category_Name { get; set; }
        public string Party_Type { get; set; }
        public string Party_Id { get; set; }
        [JsonIgnore]
        public Nullable<int> Party_Group_Code { get; set; }
        [JsonIgnore]
        public virtual ICollection<Acq_Deal> Acq_Deal { get; set; }
        [JsonIgnore]
        public virtual ICollection<Acq_Deal_Licensor> Acq_Deal_Licensor { get; set; }
        [JsonIgnore]
        public virtual ICollection<Material_Order> Material_Order { get; set; }
        [JsonIgnore]
        public virtual ICollection<Syn_Deal> Syn_Deal { get; set; }
        [JsonProperty(Order = 1)]
        public virtual ICollection<Vendor_Contacts> Vendor_Contacts { get; set; }
        [JsonProperty(Order = 2)]
        public virtual ICollection<Vendor_Country> Vendor_Country { get; set; }
        [JsonProperty(Order = 3)]
        public virtual ICollection<Vendor_Role> Vendor_Role { get; set; }
        [JsonIgnore]
        public virtual ICollection<Acq_Deal_Cost_Commission> Acq_Deal_Cost_Commission { get; set; }
        [JsonIgnore]
        public virtual ICollection<Acq_Deal_Cost_Variable_Cost> Acq_Deal_Cost_Variable_Cost { get; set; }
        [JsonIgnore]
        public virtual ICollection<Syn_Deal_Revenue_Commission> Syn_Deal_Revenue_Commission { get; set; }
        [JsonIgnore]
        public virtual ICollection<Syn_Deal_Revenue_Variable_Cost> Syn_Deal_Revenue_Variable_Cost { get; set; }
        [JsonIgnore]
        public virtual ICollection<Music_Deal> Music_Deal { get; set; }
        [JsonIgnore]
        public virtual ICollection<Music_Deal_Vendor> Music_Deal_Vendor { get; set; }
        [JsonIgnore]
        public virtual ICollection<Provisional_Deal_Licensor> Provisional_Deal_Licensor { get; set; }
        [JsonIgnore]
        public virtual ICollection<MHPlayList> MHPlayLists { get; set; }
        [JsonIgnore]
        public virtual ICollection<MHRequest> MHRequests { get; set; }
        [JsonIgnore]
        public virtual ICollection<MHCueSheet> MHCueSheets { get; set; }
        [JsonProperty(Order = 4)]
        public virtual Party_Category Party_Category { get; set; }
        [JsonProperty(Order = 5)]
        public virtual Party_Group Party_Group { get; set; }
        [JsonProperty(Order = 6)]
        public virtual ICollection<AL_Vendor_Details> AL_Vendor_Details { get; set; }
        [JsonIgnore]
        public virtual ICollection<AL_Vendor_OEM> AL_Vendor_OEM { get; set; }
        [JsonIgnore]
        public virtual ICollection<AL_Vendor_Rule> AL_Vendor_Rule { get; set; }
        [JsonIgnore]
        public virtual ICollection<AL_Vendor_TnC> AL_Vendor_TnC { get; set; }
        [JsonIgnore]
        public virtual ICollection<AL_Booking_Sheet> AL_Booking_Sheet { get; set; }
        [JsonIgnore]
        public virtual ICollection<AL_Purchase_Order_Details> AL_Purchase_Order_Details { get; set; }
        [JsonIgnore]
        public virtual ICollection<AL_Material_Tracking> AL_Material_Tracking { get; set; }
    }
}
