//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_Contacts
    {
        public Vendor_Contacts()
        {
            this.Acq_Deal = new HashSet<Acq_Deal>();
            this.Syn_Deal = new HashSet<Syn_Deal>();
        }

        [JsonIgnore]
        public State EntityState { get; set; }
        [JsonProperty(Order = -1)]
        public int Vendor_Contacts_Code { get; set; }
        [JsonProperty(Order = 1)]
        public Nullable<int> Vendor_Code { get; set; }
        [JsonProperty(Order = 2)]
        public string Contact_Name { get; set; }
        [JsonProperty(Order = 3)]
        public string Phone_No { get; set; }
        [JsonProperty(Order = 4)]
        public string Email { get; set; }
        [JsonProperty(Order = 5)]
        public string Department { get; set; }
        [JsonIgnore]
        public string _Dummy_Guid { get; set; }
        [JsonIgnore]
        public string Dummy_Guid
        {
            get
            {
                if (string.IsNullOrEmpty(_Dummy_Guid))
                    _Dummy_Guid = GetDummy_Guid();
                return _Dummy_Guid;
            }
        }
        private string GetDummy_Guid()
        {
            return Guid.NewGuid().ToString();
        }
        [JsonIgnore]
        public virtual ICollection<Acq_Deal> Acq_Deal { get; set; }
        [JsonIgnore]
        public virtual ICollection<Syn_Deal> Syn_Deal { get; set; }
        [JsonIgnore]
        public virtual Vendor Vendor { get; set; }
    }
}
