CREATE TABLE [dbo].[Acq_Rights_Template] (
    [Acq_Rights_Template_Code] INT            IDENTITY (1, 1) NOT NULL,
    [Template_Name]            VARCHAR (50)   NULL,
    [Is_Exclusive]             CHAR (1)       NULL,
    [Is_Title_Language]        CHAR (1)       NULL,
    [Is_Theatrical]            CHAR (1)       NULL,
    [Is_Sublicense]            CHAR (1)       NULL,
    [SubLicense_Code]          INT            NULL,
    [Right_Type]               CHAR (1)       NULL,
    [Term]                     VARCHAR (50)   NULL,
    [Right_Start_Date]         DATETIME       NULL,
    [Right_End_Date]           DATETIME       NULL,
    [Milestone_Type_Code]      INT            NULL,
    [Milestone_No_Of_Unit]     INT            NULL,
    [Milestone_Unit_Type]      INT            NULL,
    [ROFRDays]                 INT            NULL,
    [Region_Type]              CHAR (1)       NULL,
    [Region_Codes]             VARCHAR (1000) NULL,
    [Platform_Codes]           VARCHAR (1000) NULL,
    [Subtitling_Type]          CHAR (1)       NULL,
    [Subtitling_Codes]         VARCHAR (1000) NULL,
    [Dubbing_Type]             CHAR (1)       NULL,
    [Dubbing_Codes]            VARCHAR (1000) NULL,
    [Type]                     CHAR (1)       NULL,
    [Inserted_By]              INT            NULL,
    [Inserted_On]              DATETIME       NULL,
    [Last_Updated_Time]        DATETIME       NULL,
    [Last_Action_By]           INT            NULL,
    [Is_Active]                CHAR (1)       NULL,
    [Is_Tentative]             CHAR (1)       NULL,
    CONSTRAINT [PK_Acq_Rights_Template] PRIMARY KEY CLUSTERED ([Acq_Rights_Template_Code] ASC)
);

