CREATE TABLE [dbo].[BMS_Deal_Content_Rights] (
    [BMS_Deal_Content_Rights_Code]    INT             IDENTITY (1, 1) NOT NULL,
    [BMS_Deal_Content_Code]           INT             NULL,
    [BMS_Deal_Content_Ref_Key]        INT             NULL,
    [RU_Channel_Code]                 INT             NULL,
    [BMS_Deal_Content_Rights_Ref_Key] INT             NULL,
    [BMS_Station_Code]                INT             NULL,
    [RU_Right_Rule_Code]              INT             NULL,
    [BMS_Right_Rule_Ref_Key]          INT             NULL,
    [SAP_WBS_Code]                    INT             NULL,
    [SAP_WBS_Ref_Key]                 INT             NULL,
    [BMS_Asset_Code]                  INT             NULL,
    [BMS_Asset_Ref_Key]               INT             NULL,
    [Asset_Type]                      VARCHAR (3)     NULL,
    [Title]                           VARCHAR (80)    NULL,
    [License_Fees]                    DECIMAL (18, 3) NULL,
    [Total_Runs]                      INT             NULL,
    [Utilised_Run]                    INT             NULL,
    [Start_Date]                      DATETIME        NULL,
    [End_Date]                        DATETIME        NULL,
    [Blackout_From_1]                 DATETIME        NULL,
    [Blackout_To_1]                   DATETIME        NULL,
    [Blackout_From_2]                 DATETIME        NULL,
    [Blackout_To_2]                   DATETIME        NULL,
    [Blackout_From_3]                 DATETIME        NULL,
    [Blackout_To_3]                   DATETIME        NULL,
    [Request_Time]                    DATETIME        NULL,
    [Response_Time]                   DATETIME        NULL,
    [Record_Status]                   VARCHAR (5)     NULL,
    [Error_Description]               VARCHAR (4000)  NULL,
    [Is_Archived]                     VARCHAR (5)     NULL,
    [YearWise_No]                     INT             NULL,
    [Min_Runs]                        INT             NULL,
    [Max_Runs]                        INT             NULL,
    [Acq_Deal_Rights_Code]            INT             NULL,
    [Acq_Deal_Run_Code]               INT             NULL,
    [Acq_Deal_Run_Channel_Code]       INT             NULL,
    [Acq_Deal_Run_YearWise_Run_Code]  INT             NULL,
    CONSTRAINT [PK_BMS_Deal_Content_Rights] PRIMARY KEY CLUSTERED ([BMS_Deal_Content_Rights_Code] ASC),
    CONSTRAINT [FK_BMS_Deal_Content_Rights_BMS_Deal_Content] FOREIGN KEY ([BMS_Deal_Content_Code]) REFERENCES [dbo].[BMS_Deal_Content] ([BMS_Deal_Content_Code])
);



