CREATE TABLE [dbo].[DM_BMS_Mapped_UnMapped_Deal] (
    [DM_BMS_Mapped_UnMapped_Deal_Code] INT             IDENTITY (1, 1) NOT NULL,
    [BMS_Deal_Code]                    INT             NULL,
    [Acq_Deal_Code]                    INT             NULL,
    [BMS_Deal_Ref_Key]                 INT             NULL,
    [Is_Archived]                      VARCHAR (5)     NULL,
    [RU_Licensor_Code]                 INT             NULL,
    [RU_Payee_Code]                    INT             NULL,
    [RU_Currency_Code]                 INT             NULL,
    [RU_Licensee_Code]                 INT             NULL,
    [RU_Category_Code]                 INT             NULL,
    [BMS_Licensor_Code]                INT             NULL,
    [BMS_Payee_Code]                   INT             NULL,
    [BMS_Currency_Code]                INT             NULL,
    [BMS_Licensee_Code]                INT             NULL,
    [BMS_Category_Code]                INT             NULL,
    [License_Fees]                     DECIMAL (18, 3) NULL,
    [Description]                      VARCHAR (80)    NULL,
    [Contact]                          VARCHAR (80)    NULL,
    [Lic_Ref_No]                       VARCHAR (20)    NULL,
    [Revision]                         VARCHAR (40)    NULL,
    [Start_Date]                       DATETIME        NULL,
    [End_Date]                         DATETIME        NULL,
    [Status_SLUId]                     INT             NULL,
    [Type_SLUId]                       INT             NULL,
    [Acquisition_Date]                 DATETIME        NULL,
    [DEA_ID]                           VARCHAR (MAX)   NULL,
    [DEA_ISARCHIVED]                   VARCHAR (MAX)   NULL,
    [DEA_NUMBER]                       VARCHAR (MAX)   NULL,
    [DEA_COM_ID_LICENSOR]              VARCHAR (MAX)   NULL,
    [DEA_COM_ID_PAYEE]                 VARCHAR (MAX)   NULL,
    [DEA_CUR_ID]                       VARCHAR (MAX)   NULL,
    [DEA_SLU_ID_DEALSTATUS]            VARCHAR (MAX)   NULL,
    [DEA_CHA_ID_LICENSEE]              VARCHAR (MAX)   NULL,
    [DEA_DEC_ID]                       VARCHAR (MAX)   NULL,
    [DEA_SLU_ID_TYPE]                  VARCHAR (MAX)   NULL,
    [DEA_LICENSEFEE]                   VARCHAR (MAX)   NULL,
    [DEA_STARTDATE]                    VARCHAR (MAX)   NULL,
    [DEA_ENDDATE]                      VARCHAR (MAX)   NULL,
    [DEA_DESC]                         VARCHAR (MAX)   NULL,
    [DEA_CONTRACTNO]                   VARCHAR (MAX)   NULL,
    [DEA_REVISION]                     VARCHAR (MAX)   NULL,
    [DEA_LICENSORREFERENCENO]          VARCHAR (MAX)   NULL,
    [DEA_GNR_ID]                       VARCHAR (MAX)   NULL,
    [DEA_FOREIGNID]                    VARCHAR (MAX)   NULL,
    [DEA_UPDATEDATETIME]               VARCHAR (MAX)   NULL,
    [DEA_UPDATEUSERID]                 VARCHAR (MAX)   NULL,
    [Request_Time]                     DATETIME        NULL,
    [Response_Time]                    DATETIME        NULL,
    [Record_Status]                    VARCHAR (5)     NULL,
    [IS_Mapped]                        CHAR (1)        NULL,
    [IS_Error]                         VARCHAR (2000)  NULL,
    [Exact_Deal_Match]                 VARCHAR (100)   NULL,
    [Error_Description]                VARCHAR (MAX)   NULL
);

