CREATE TABLE [dbo].[DM_BMS_Mapped_UnMapped_Content] (
    [DM_BMS_Mapped_UnMapped_Content_Code] INT           IDENTITY (1, 1) NOT NULL,
    [BMS_Deal_Code]                       INT           NULL,
    [BMS_Deal_Content_Code]               INT           NULL,
    [BMS_Deal_Ref_Key]                    INT           NULL,
    [BMS_Deal_Content_Ref_Key]            INT           NULL,
    [BMS_Asset_Code]                      INT           NULL,
    [BMS_Asset_Ref_Key]                   INT           NULL,
    [Asset_Type]                          VARCHAR (3)   NULL,
    [Title]                               VARCHAR (80)  NULL,
    [Start_Date]                          DATETIME      NULL,
    [End_Date]                            DATETIME      NULL,
    [Request_Time]                        DATETIME      NULL,
    [Response_Time]                       DATETIME      NULL,
    [Record_Status]                       VARCHAR (5)   NULL,
    [Error_Description]                   VARCHAR (MAX) NULL,
    [Is_Archived]                         VARCHAR (5)   NULL,
    [DCO_ID]                              INT           NULL,
    [DCO_Asset_ID]                        INT           NULL,
    [DCO_Start_Date]                      VARCHAR (100) NULL,
    [DCO_End_Date]                        VARCHAR (100) NULL,
    [DCO_Deal_Id]                         INT           NULL,
    [RU_Content_Count]                    INT           NULL,
    [BU_Content_Count]                    INT           NULL,
    [IS_Mapped]                           CHAR (1)      NULL,
    [IS_Error]                            CHAR (1)      NULL,
    [Exact_Deal_Match]                    VARCHAR (100) NULL
);

