CREATE TABLE [dbo].[DM_BMS_DEAL_CONTENT] (
    [DCO_ID]                VARCHAR (MAX) NULL,
    [DCO_DEA_ID]            VARCHAR (MAX) NULL,
    [DCO_ASSETTYPE]         VARCHAR (MAX) NULL,
    [DCO_ASS_ID]            VARCHAR (MAX) NULL,
    [DCO_TITLE]             VARCHAR (MAX) NULL,
    [DCO_DATEAVAILABLEFROM] VARCHAR (MAX) NULL,
    [DCO_DATEAVAILABLETO]   VARCHAR (MAX) NULL,
    [DCO_FOREIGNID]         VARCHAR (MAX) NULL
);

