CREATE TABLE [dbo].[DM_BMS_DEAL] (
    [DEA_ID]                  VARCHAR (MAX) NULL,
    [DEA_ISARCHIVED]          VARCHAR (MAX) NULL,
    [DEA_NUMBER]              VARCHAR (MAX) NULL,
    [DEA_COM_ID_LICENSOR]     VARCHAR (MAX) NULL,
    [DEA_COM_ID_PAYEE]        VARCHAR (MAX) NULL,
    [DEA_CUR_ID]              VARCHAR (MAX) NULL,
    [DEA_SLU_ID_DEALSTATUS]   VARCHAR (MAX) NULL,
    [DEA_CHA_ID_LICENSEE]     VARCHAR (MAX) NULL,
    [DEA_DEC_ID]              VARCHAR (MAX) NULL,
    [DEA_SLU_ID_TYPE]         VARCHAR (MAX) NULL,
    [DEA_LICENSEFEE]          VARCHAR (MAX) NULL,
    [DEA_STARTDATE]           VARCHAR (MAX) NULL,
    [DEA_ENDDATE]             VARCHAR (MAX) NULL,
    [DEA_DESC]                VARCHAR (MAX) NULL,
    [DEA_CONTRACTNO]          VARCHAR (MAX) NULL,
    [DEA_REVISION]            VARCHAR (MAX) NULL,
    [DEA_LICENSORREFERENCENO] VARCHAR (MAX) NULL,
    [DEA_GNR_ID]              VARCHAR (MAX) NULL,
    [DEA_FOREIGNID]           VARCHAR (MAX) NULL,
    [DEA_UPDATEDATETIME]      VARCHAR (MAX) NULL,
    [DEA_UPDATEUSERID]        VARCHAR (MAX) NULL
);

