CREATE TABLE [dbo].[Email_Notification_Schedule_Show] (
    [Email_Notification_Schedule_Show_Code] NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [BV_Schedule_Transaction_Show_Code]     NUMERIC (18)   NULL,
    [Program_Episode_Title]                 VARCHAR (500)  NULL,
    [Program_Episode_Number]                VARCHAR (50)   NULL,
    [Program_Title]                         VARCHAR (500)  NULL,
    [Program_Category]                      VARCHAR (100)  NULL,
    [Schedule_Item_Log_Date]                VARCHAR (50)   NULL,
    [Schedule_Item_Log_Time]                VARCHAR (50)   NULL,
    [Schedule_Item_Duration]                VARCHAR (50)   NULL,
    [Scheduled_Version_House_Number_List]   VARCHAR (1000) NULL,
    [File_Code]                             BIGINT         NULL,
    [Channel_Code]                          INT            NULL,
    [Inserted_On]                           DATETIME       NULL,
    [Deal_Movie_Code]                       NUMERIC (18)   NULL,
    [Deal_Movie_Rights_Code]                NUMERIC (18)   NULL,
    [Email_Notification_Msg]                VARCHAR (5000) NULL,
    [IsMailSent]                            CHAR (1)       NULL,
    [IsRunCountCalculate]                   CHAR (1)       NULL,
    [Title_Code]                            INT            NULL,
    [Title_Name]                            VARCHAR (500)  NULL,
    [Right_Start_Date]                      DATETIME       NULL,
    [Right_End_Date]                        DATETIME       NULL,
    [No_Of_Runs_Across_Beams]               VARCHAR (50)   NULL,
    [Available_Channels]                    VARCHAR (500)  NULL,
    [Count_Of_Schedule]                     VARCHAR (50)   NULL,
    [Channel_Name]                          VARCHAR (250)  NULL,
    [Deal_Movie_Content_Code]               INT            NULL,
    [Episode_No]                            VARCHAR (100)  NULL,
    [RightsPeriod]                          VARCHAR (100)  NULL,
    CONSTRAINT [PK_Email_Notification_Schedule_Show] PRIMARY KEY CLUSTERED ([Email_Notification_Schedule_Show_Code] ASC)
);

