//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHPlayList
    {
        public MHPlayList()
        {
            this.MHPlayListSongs = new HashSet<MHPlayListSong>();
        }
    
    	public State EntityState { get; set; }    public int MHPlayListCode { get; set; }
    	    public string PlaylistName { get; set; }
    	    public Nullable<int> TitleCode { get; set; }
    	    public Nullable<int> VendorCode { get; set; }
    	    public string IsActive { get; set; }
    
        public virtual Title Title { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<MHPlayListSong> MHPlayListSongs { get; set; }
    }
}
