//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;

    public partial class MHRequest
    {
        public MHRequest()
        {
            this.MHRequestDetails = new HashSet<MHRequestDetail>();
        }

        public State EntityState { get; set; }
        public long MHRequestCode { get; set; }
        public Nullable<int> MHRequestTypeCode { get; set; }
        public string RequestID { get; set; }
        public Nullable<int> VendorCode { get; set; }
        public Nullable<int> TitleCode { get; set; }
        public Nullable<int> EpisodeFrom { get; set; }
        public Nullable<int> EpisodeTo { get; set; }
        public Nullable<System.DateTime> TelecastFrom { get; set; }
        public Nullable<System.DateTime> TelecastTo { get; set; }
        public Nullable<int> UsersCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<int> MHRequestStatusCode { get; set; }
        public string SpecialInstruction { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> ChannelCode { get; set; }
        public string InternalRemarks { get; set; }

        public virtual MHRequestStatu MHRequestStatu { get; set; }
        public virtual MHRequestType MHRequestType { get; set; }
        public virtual Title Title { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<MHRequestDetail> MHRequestDetails { get; set; }
        public virtual Channel Channel { get; set; }
    }
}
