//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Content_Status_History
    {
        public State EntityState { get; set; }
        public int Content_Status_History_Code { get; set; }
        public Nullable<int> User_Code { get; set; }
        public string User_Action { get; set; }
        public Nullable<int> Record_Count { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> Title_Content_Code { get; set; }
        public virtual Title_Content Title_Content { get; set; }
    }
}
