//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Music_Override_Reason
    {
        public State EntityState { get; set; }    public int Music_Override_Reason_Code { get; set; }
        public string Music_Override_Reason_Name { get; set; }
    }
}
