CREATE TABLE [dbo].[Avail_Report_Schedule] (
    [Avail_Report_Schedule_code] INT             IDENTITY (1, 1) NOT NULL,
    [Title_Code]                 VARCHAR (MAX)   NULL,
    [Platform_Code]              VARCHAR (MAX)   NULL,
    [Country_Code]               VARCHAR (MAX)   NULL,
    [Is_Original_Language]       BIT             NULL,
    [Dubbing_Subtitling]         VARCHAR (20)    NULL,
    [GroupBy]                    VARCHAR (1)     NULL,
    [Node]                       VARCHAR (1)     NULL,
    [Language_Code]              VARCHAR (MAX)   NULL,
    [Date_Type]                  VARCHAR (2)     NULL,
    [StartDate]                  VARCHAR (20)    NULL,
    [EndDate]                    VARCHAR (20)    NULL,
    [User_Code]                  INT             NULL,
    [Inserted_On]                DATETIME        NULL,
    [Report_Status]              CHAR (1)        NULL,
    [Report_File_Name]           VARCHAR (500)   NULL,
    [ShowRemark]                 VARCHAR (10)    NULL,
    [Email_Status]               CHAR (1)        NULL,
    [Visibility]                 CHAR (2)        NULL,
    [ReportName]                 NVARCHAR (1000) NULL,
    [RestrictionRemarks]         VARCHAR (MAX)   NULL,
    [OthersRemark]               VARCHAR (MAX)   NULL,
    [Platform_ExactMatch]        CHAR (10)       NULL,
    [MustHave_Platform]          VARCHAR (MAX)   NULL,
    [Exclusivity]                CHAR (1)        NULL,
    [SubLicense_Code]            VARCHAR (MAX)   NULL,
    [Region_ExactMatch]          CHAR (10)       NULL,
    [Region_MustHave]            VARCHAR (MAX)   NULL,
    [Region_Exclusion]           VARCHAR (MAX)   NULL,
    [Subtit_Language_Code]       VARCHAR (MAX)   NULL,
    [Dubbing_Language_Code]      VARCHAR (MAX)   NULL,
    [BU_Code]                    INT             NULL,
    [Report_Type]                CHAR (2)        NULL,
    [Digital]                    BIT             NULL,
    [IncludeMetadata]            VARCHAR (50)    NULL
);



