//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Acq_Deal_Mass_Territory_Update
    {
        public Acq_Deal_Mass_Territory_Update()
        {
            this.Acq_Deal_Mass_Territory_Update_Details = new HashSet<Acq_Deal_Mass_Territory_Update_Details>();
            this.Acq_Deal_Mass_Update_ErrorLog = new HashSet<Acq_Deal_Mass_Update_ErrorLog>();
        }

        public State EntityState { get; set; }
        public int Acq_Deal_Mass_Update_Code { get; set; }
        public Nullable<int> Acq_Deal_Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Processed_Date { get; set; }
        public string Can_Process { get; set; }
        public Nullable<int> Created_By { get; set; }

        public virtual Acq_Deal Acq_Deal { get; set; }
        public virtual ICollection<Acq_Deal_Mass_Territory_Update_Details> Acq_Deal_Mass_Territory_Update_Details { get; set; }
        public virtual ICollection<Acq_Deal_Mass_Update_ErrorLog> Acq_Deal_Mass_Update_ErrorLog { get; set; }
    }
}
