//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Acq_Deal_Mass_Territory_Update_Details
    {
        public State EntityState { get; set; }    
        public int Acq_Deal_Mass_Update_Det_Code { get; set; }
        public Nullable<int> Acq_Deal_Mass_Update_Code { get; set; }
        public Nullable<int> Territory_Code { get; set; }

        public virtual Acq_Deal_Mass_Territory_Update Acq_Deal_Mass_Territory_Update { get; set; }
        public virtual Territory Territory { get; set; }
    }
}
