//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acq_Deal_Rights_Holdback_Dubbing
    {
        public State EntityState { get; set; }
        public int Acq_Deal_Rights_Holdback_Dubbing_Code { get; set; }
        public Nullable<int> Acq_Deal_Rights_Holdback_Code { get; set; }
        public Nullable<int> Language_Code { get; set; }
    
        public virtual Acq_Deal_Rights_Holdback Acq_Deal_Rights_Holdback { get; set; }
        public virtual Language Language { get; set; }
    }
}
