//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acq_Deal_Pushback_Subtitling
    {
        public State EntityState { get; set; }
        public int Acq_Deal_Pushback_Subtitling_Code { get; set; }
        public Nullable<int> Acq_Deal_Pushback_Code { get; set; }
        public string Language_Type { get; set; }
        public Nullable<int> Language_Code { get; set; }
        public Nullable<int> Language_Group_Code { get; set; }
    
        public virtual Acq_Deal_Pushback Acq_Deal_Pushback { get; set; }
        public virtual Language Language { get; set; }
        public virtual Language_Group Language_Group { get; set; }
    }
}
