//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acq_Deal_Budget
    {
    	public State EntityState { get; set; }    public int Acq_Deal_Budget_Code { get; set; }
    	    public Nullable<int> Acq_Deal_Code { get; set; }
    	    public Nullable<int> Title_Code { get; set; }
    	    public Nullable<int> Episode_From { get; set; }
    	    public Nullable<int> Episode_To { get; set; }
    	    public Nullable<int> SAP_WBS_Code { get; set; }
    
        public virtual Acq_Deal Acq_Deal { get; set; }
        public virtual Title Title { get; set; }
        public virtual SAP_WBS SAP_WBS { get; set; }
    }
}
