//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Avail_Acq_Language
    {
        public State EntityState { get; set; }
        public decimal Avail_Acq_Language1 { get; set; }
        public Nullable<decimal> Avail_Acq_Code { get; set; }
        public string Dubbing_Subtitling { get; set; }
        public Nullable<int> Language_Code { get; set; }
        public Nullable<System.DateTime> Rights_Start_Date { get; set; }
        public Nullable<System.DateTime> Rights_End_Date { get; set; }
        public Nullable<int> Acq_Deal_Code { get; set; }

        public virtual Avail_Acq Avail_Acq { get; set; }
    }
}
