//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rights_Bulk_Update
    {
    	public State EntityState { get; set; }    public int Rights_Bulk_Update_Code { get; set; }
    	    public Nullable<int> Deal_Code { get; set; }
    	    public string Right_Codes { get; set; }
    	    public string Change_For { get; set; }
    	    public string Action_For { get; set; }
    	    public Nullable<System.DateTime> Start_Date { get; set; }
    	    public Nullable<System.DateTime> End_Date { get; set; }
    	    public string Term { get; set; }
    	    public string Milestone_Type_Code { get; set; }
    	    public string Milestone_No_Of_Unit { get; set; }
    	    public string Milestone_Unit_Type { get; set; }
    	    public string Rights_Type { get; set; }
    	    public string Codes { get; set; }
    	    public string Is_Exclusive { get; set; }
    	    public string Is_Title_Language { get; set; }
    	    public string Is_Tentative { get; set; }
    	    public string SelectedTitleCodes { get; set; }
    	    public string SelectedTitleNames { get; set; }
    	    public string Is_Syn_Acq_Mapp { get; set; }
    	    public string Page_View { get; set; }
    	    public Nullable<System.DateTime> Inserted_On { get; set; }
    	    public string Is_Processed { get; set; }
    }
}
