
if not exists (select * from System_Parameter_New where Parameter_name = 'Is_RU_Content_Category' )
begin
INSERT INTO System_Parameter_New (Parameter_Name,Parameter_Value, IsActive)
SELECT 'Is_RU_Content_Category' ,'Y','Y'
end


			UPDATE Email_Template SET template_desc = '<html>
	<head>
		<style type="text/css">
			table.tblFormat
			{
				border:1px solid black;
				border-collapse:collapse;
			}
			td.tblHead
			{
				border:1px solid black;  
				color: #ffffff ; 
				background-color: #585858;
				font-family:verdana;
				font-size:12px;
			}
			td.tblData
			{
				border:1px solid black; 
				vertical-align:top;
				font-family:verdana;
				font-size:12px;
			}
			
			.textFont
			{
				color: black ; 
				font-family:verdana;
				font-size:12px;
			}
			
			#divFooter
			{
				color: gray;
			}
		</style>
	</head>
	<body>
		<div class="textFont">
			Dear&nbsp;{login_name},<br /><br />
			The {deal_type} Deal No: <b>{deal_no}</b> is rejected by <b>{rejected_by}</b>.<br /><br />
			Please <a href=''{link}'' target=''_blank''><b>click here</b></a> for more details.<br /><br /><br /><br />
		</div>
		{table}
		<br /><br /><br /><br />
		<div id="divFooter" class="textFont">
			This email is generated by RightsU
		</div>
	</body>
</html>'  WHERE Template_For='R'

UPDATE Email_template SET template_desc = 
'<html>
	<head>
		<style type="text/css">
			table.tblFormat
			{
				border:1px solid black;
				border-collapse:collapse;
			}
			th.tblHead
			{
				border:1px solid black;  
				color: #ffffff ; 
				background-color: #585858;
				font-family:verdana;
				font-size:12px;
			}
			td.tblData
			{
				border:1px solid black; 
				vertical-align:top;
				font-family:verdana;
				font-size:12px;
			}
			
			.textFont
			{
				color: black ; 
				font-family:verdana;
				font-size:12px;
			}
			
			#divFooter
			{
				color: gray;
			}
		</style>
	</head>
	<body>
		<div class="textFont">
			Dear &nbsp;{login_name},<br /><br />
			The {deal_type} Deal No: <b>{deal_no}</b> is sent to {next_approval} for approval.<br /><br />
			Please <a href=''{link}'' target=''_blank''><b>click here</b></a> for more details.<br /><br /><br /><br />
		</div>
		{table}
		<br /><br />
		<div id="divFooter" class="textFont">
			This email is generated by RightsU
		</div>
	</body>
</html>' WHERE Template_For='I'

----------------------------------------
UPDATE Email_template SET template_desc = 
'<html>
	<head>
		<style>
			table.tblFormat
			{
				border:1px solid black;
				border-collapse:collapse;
			}
			th.tblHead
			{
				border:1px solid black;  
				color: #ffffff ; 
				background-color: #585858;
				font-family:verdana;
				font-size:12px;
			}
			td.tblData
			{
				border:1px solid black; 
				vertical-align:top;
				font-family:verdana;
				font-size:12px;
			}
			
			.textFont
			{
				color: black ; 
				font-family:verdana;
				font-size:12px;
			}
			
			#divFooter
			{
				color: gray;
			}
		</style>
	</head>
	<body>
		<div class="textFont">
			Dear &nbsp;{login_name},<br /><br />
			The {deal_type} Deal No: <b>{deal_no}</b> is approved by <b> {approved_by}</b>.<br /><br />
			Please <a href=''{link}'' target=''_blank''><b>click here</b></a> for more details.<br /><br /><br />
		</div>
	{table}
		<br /><br />
		<div id="divFooter" class="textFont">
			This email is generated by RightsU
		</div>
	</body>
</html>' WHERE Template_For='D'


UPDATE Email_Template SET template_desc = '
<html>
	<head>
		<style>
			table.tblFormat
			{
				border:1px solid black;
				border-collapse:collapse;
			}
			td.tblHead
			{
				border:1px solid black;  
				color: #ffffff ; 
				background-color: #585858;
				font-family:verdana;
				font-size:12px;
			}
			td.tblData
			{
				border:1px solid black; 
				vertical-align:top;
				font-family:verdana;
				font-size:12px;
			}
			
			.textFont
			{
				color: black ; 
				font-family:verdana;
				font-size:12px;
			}
			
			#divFooter
			{
				color: gray;
			}
		</style>
	</head>
	<body>
		<div class="textFont">
			Dear&nbsp;{login_name},<br /><br />
			The {deal_type} Deal No: <b>{deal_no}</b> is waiting for approval.<br /><br />
			Please <a href=''{link}'' target=''_blank''><b>click here</b></a> to approve {deal_type} deal<br /><br />
		</div>
		{table}
		<br /><br /><br /><br />
		<div id="divFooter" class="textFont">
			This email is generated by RightsU
		</div>
	</body>
</html>'
 WHERE Template_For='A'