export enum LABELS {
  LOADING_TEXT = 'Loading',
  SEARCH_SCREEN = 'Notification Engine Search Screen',
  EVENT = 'Event / Category',
  Transaction_Type = 'Transaction Type',
  Message_Type = 'Message Type',
  Transaction_Code = 'Transaction Code',
  Status = 'Status',
  Message = 'Message',
  Sent_To = 'Sent To',
  No_Of_Retry = 'No Of Retry',
  Notification_Type = 'Notification Type',
  User = 'User',
  Recipient = 'Recipient',
  Subject = 'Subject',
  Schedule_Date_Time_Between = 'Schedule Date Time Between',
  Sent_Date_Time_Between = 'Sent Date Time Between',
  Sent_Date_Time = ' Sent Date Time',
  Schedule_Date_Time = 'Schedule Date Time',
  Start_Date = 'Start Date Time',
  End_Date = 'End Date Time',
  Time = 'Time',
  Search = 'Search',
  Export_CSV = 'Export CSV',
  View = 'View',
  Resend = 'Resend',
  No_Records_Found = 'No Records Found',
  Action = 'Action',
  Yes = 'Yes',
  No = 'No',
  Config_Screen = 'Notification Engine Configuration Screen',
  Retry_Option_For_Failed_Msg = 'Retry Option For Failed Msg',
  Retry_Option_For_Success_Msg = 'Retry Option For Success Msg',
  Duration_Between = 'Duration Between Two Retries in Min',
  SMTP_SERVER = 'SMTP Server Name/IP',
  SMTP_Port = 'SMTP Port',
  Use_Default_Credentials = 'Use Default Credentials',
  User_Name = 'User Name',
  Password = 'Password',
  Save = 'Save',
  Cancel = 'Cancel',
  SearchScreen = 'Search Screen',
  ConfigurationScreen = 'Configuration Screen'

}

export enum MESSAGES {
  This_field_is_required = 'This field is required',
  Period_Validation = 'Period cannot be more than 3 months',
  Are_Sure_Want_To_Resend = 'Are you sure you want to resend ?'
}
