//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Dapper.Entity
{
    using Dapper.SimpleSave;
    using System;
    using System.Collections.Generic;

    [Table("Music_Deal_DealType")]
    public partial class Music_Deal_DealType
    {
        [PrimaryKey]
        public int? Music_Deal_Type_Code { get; set; }
        [ForeignKeyReference(typeof(Music_Deal))]
        public int Music_Deal_Code { get; set; }
        [ForeignKeyReference(typeof(Deal_Type))]
        public int Deal_Type_Code { get; set; }
        //public virtual Deal_Type Deal_Type { get; set; }

        //public virtual Music_Deal_Dapper Music_Deal { get; set; }
    }
}
