//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Dapper.Entity
{
    using Dapper.SimpleSave;
    using System;
    using System.Collections.Generic;

    [Table("Music_Deal_LinkShow")]
    public partial class Music_Deal_LinkShow_Dapper
    {
        [PrimaryKey]
        public int? Music_Deal_LinkShow_Code { get; set; }
        [ForeignKeyReference(typeof(Music_Deal_Dapper))]
        public Nullable<int> Music_Deal_Code { get; set; }
        public Nullable<int> Title_Code { get; set; }
    
        //public virtual Music_Deal_Dapper Music_Deal { get; set; }
    }
}
