CREATE TABLE [dbo].[Show_Avail_Data] (
    [Title_Name]                  NVARCHAR (MAX) NULL,
    [Episode_From]                INT            NULL,
    [Episode_To]                  INT            NULL,
    [Platform_Name]               NVARCHAR (MAX) NULL,
    [COL1]                        NVARCHAR (MAX) NULL,
    [COL2]                        NVARCHAR (MAX) NULL,
    [COL3]                        NVARCHAR (MAX) NULL,
    [Right_Start_Date]            NVARCHAR (MAX) NULL,
    [Rights_End_Date]             NVARCHAR (MAX) NULL,
    [Title_Language_Names]        NVARCHAR (MAX) NULL,
    [Sub_Language_Names]          NVARCHAR (MAX) NULL,
    [Dub_Language_Names]          NVARCHAR (MAX) NULL,
    [Genres_Name]                 NVARCHAR (MAX) NULL,
    [Star_Cast]                   NVARCHAR (MAX) NULL,
    [Director]                    NVARCHAR (MAX) NULL,
    [Duration_In_Min]             VARCHAR (10)   NULL,
    [Year_Of_Production]          VARCHAR (10)   NULL,
    [Restriction_Remark]          NVARCHAR (MAX) NULL,
    [Sub_Deal_Restriction_Remark] NVARCHAR (MAX) NULL,
    [Remarks]                     NVARCHAR (MAX) NULL,
    [Rights_Remarks]              NVARCHAR (MAX) NULL,
    [Exclusive]                   VARCHAR (20)   NULL,
    [Sub_License]                 VARCHAR (100)  NULL,
    [Platform_Avail]              VARCHAR (3)    NULL,
    [Ancillary_Rights]            NVARCHAR (MAX) NULL,
    [BU_Code]                     INT            NULL
);

