CREATE TABLE [dbo].[Syn_Deal] (
    [Syn_Deal_Code]            INT             IDENTITY (1, 1) NOT NULL,
    [Deal_Type_Code]           INT             NULL,
    [Business_Unit_Code]       INT             NULL,
    [Other_Deal]               VARCHAR (100)   NULL,
    [Agreement_No]             VARCHAR (50)    NULL,
    [Version]                  VARCHAR (50)    NULL,
    [Agreement_Date]           DATETIME        NULL,
    [Deal_Description]         NVARCHAR (250)  NULL,
    [Status]                   CHAR (1)        NULL,
    [Total_Sale]               FLOAT (53)      NULL,
    [Year_Type]                CHAR (2)        NULL,
    [Customer_Type]            INT             NULL,
    [Vendor_Code]              INT             NULL,
    [Vendor_Contact_Code]      INT             NULL,
    [Sales_Agent_Code]         INT             NULL,
    [Sales_Agent_Contact_Code] INT             NULL,
    [Entity_Code]              INT             NULL,
    [Currency_Code]            INT             NULL,
    [Exchange_Rate]            NUMERIC (10, 3) NULL,
    [Ref_No]                   NVARCHAR (50)   NULL,
    [Attach_Workflow]          CHAR (1)        NULL,
    [Deal_Workflow_Status]     VARCHAR (50)    NULL,
    [Work_Flow_Code]           INT             NULL,
    [Is_Completed]             CHAR (1)        NULL,
    [Category_Code]            INT             NULL,
    [Parent_Syn_Deal_Code]     INT             NULL,
    [Is_Migrated]              CHAR (1)        NULL,
    [Payment_Terms_Conditions] NVARCHAR (4000) NULL,
    [Deal_Tag_Code]            INT             NULL,
    [Ref_BMS_Code]             VARCHAR (100)   NULL,
    [Remarks]                  NVARCHAR (4000) NULL,
    [Rights_Remarks]           NVARCHAR (4000) NULL,
    [Payment_Remarks]          NVARCHAR (4000) NULL,
    [Is_Active]                CHAR (1)        NULL,
    [Deal_Complete_Flag]       VARCHAR (100)   NULL,
    [Inserted_On]              DATETIME        NULL,
    [Inserted_By]              INT             NULL,
    [Lock_Time]                DATETIME        NULL,
    [Last_Updated_Time]        DATETIME        NULL,
    [Last_Action_By]           INT             NULL,
    [Role_Code]                INT             NULL,
    [Deal_Segment_Code]        INT             NULL,
    [Revenue_Vertical_Code]    INT             NULL,
    CONSTRAINT [PK_Syn_Deal] PRIMARY KEY CLUSTERED ([Syn_Deal_Code] ASC)
);



