CREATE TABLE [dbo].[Avail_Titles] (
    [Avail_TitlesCode]     INT             IDENTITY (1, 1) NOT NULL,
    [TitleCode]            INT             NULL,
    [TitleName]            NVARCHAR (500)  NULL,
    [Vendor_Code]          INT             NULL,
    [Vendor_Name]          NVARCHAR (200)  NULL,
    [OriginalLanguageCode] INT             NULL,
    [OriginalLanguage]     DECIMAL (18, 3) NULL,
    [ContentLanguageCode]  INT             NULL,
    [ContentLanguage]      DECIMAL (18, 3) NULL,
    [StarCastCode]         NVARCHAR (MAX)  NULL,
    [StarCast]             DECIMAL (18, 3) NULL,
    [GenreCode]            NVARCHAR (MAX)  NULL,
    [Genre]                DECIMAL (18, 3) NULL,
    [ReleaseYearCode]      INT             NULL,
    [ReleaseYear]          DECIMAL (18, 3) NULL,
    [BannerCode]           NVARCHAR (MAX)  NULL,
    [Banner]               DECIMAL (18, 3) NULL,
    [TypeOfFilmCode]       NVARCHAR (MAX)  NULL,
    [TypeOfFilm]           DECIMAL (18, 3) NULL,
    [IMDBRatingsCode]      NVARCHAR (MAX)  NULL,
    [IMDBRatings]          DECIMAL (18, 3) NULL,
    [AwardsCode]           NVARCHAR (MAX)  NULL,
    [Awards]               DECIMAL (18, 3) NULL,
    [PlatformCode]         NVARCHAR (MAX)  NULL,
    [Platform]             DECIMAL (18, 3) NULL,
    [TerritoryCode]        NVARCHAR (MAX)  NULL,
    [Territory]            DECIMAL (18, 3) NULL,
    [Exclusivity]          INT             NULL,
    [AverageMovieRatings]  DECIMAL (18, 3) NULL,
    CONSTRAINT [PK_Avail_Titles] PRIMARY KEY CLUSTERED ([Avail_TitlesCode] ASC)
);

