//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightsU_Entities
{
    using System;
    using System.Collections.Generic;

    public partial class AL_Booking_Sheet_Details
    {
        public State EntityState { get; set; }
        public int AL_Booking_Sheet_Details_Code { get; set; }
        public Nullable<int> AL_Booking_Sheet_Code { get; set; }
        public Nullable<int> Title_Code { get; set; }
        public Nullable<int> Title_Content_Code { get; set; }
        public Nullable<int> Extended_Group_Code { get; set; }
        public Nullable<int> Columns_Code { get; set; }
        public Nullable<int> Group_Control_Order { get; set; }
        public string Validations { get; set; }
        public string Additional_Condition { get; set; }
        public string Display_Name { get; set; }
        public string Allow_Import { get; set; }
        public string Columns_Value { get; set; }
        public string Cell_Status { get; set; }

        public virtual AL_Booking_Sheet AL_Booking_Sheet { get; set; }
        public virtual Extended_Columns Extended_Columns { get; set; }
        public virtual Extended_Group Extended_Group { get; set; }
        public virtual Title Title { get; set; }
        public virtual Title_Content Title_Content { get; set; }
    }
}
